### ISSUE TITLE
yellow warning in android

### ISSUE THREAD

**Issue by Momazo7u7** [react-native-community/react-native-webview#297] opened 2019-01-31 17:10 UTC
steps to reproduce 
in the webview load www.google.com
 <WebView
        source={{ uri: 'https://www.google.com' }}/>

click on the google logo

It displays:

```
 Warning
Accessing view manager configs directly off UIManager via UIManager['RNCWebView'] is no longer supported. Use UIManager.getViewManagerConfig('RNCWebView') instead.
```

```
"dependencies": {
    "react": "16.6.3",
    "react-native": "0.58.1",
    "react-native-gesture-handler": "^1.0.15",
    "react-native-modal": "^7.0.2",
    "react-native-size-matters": "^0.1.6",
    "react-native-vector-icons": "^6.2.0",
    "react-native-webview": "^4.0.0",
    "react-navigation": "^3.0.9",
    "reactn": "^0.1.9"
  },
```

after looking at the report, it seems that it's pointing at node_modules/react-native-webview/js/WebView.android.js line 314 "UIManager.RNCWebView.Commands.loadUrl" , it needs a change at all "UIManager.RNCWebView" calls

**Comment by Titozzz** [comment] 2019-02-01 01:16
Closing as duplicate of #279

**Closed by Titozzz** 2019-02-01 01:16 UTC
Labels: question
