### ISSUE TITLE
Android Clean Build Failed Using Gradle 6.0

### ISSUE THREAD

**Issue by crocoapps** [react-native-community/react-native-webview#1011] opened 2019-11-11 03:33 UTC
Android Clean Build Failed Using Gradle 6.0

I'm just trying Gradle 6.0, update gradle to 6.0 and clean the android build

**Expected behavior:**

Clean build success

**Screenshots/Videos:**

FAILURE: Build failed with an exception.

* Where:
Build file '/Volumes/DATA/Projects/EzFit/node_modules/react-native-webview/android/build.gradle' line: 26

* What went wrong:
A problem occurred evaluating project ':react-native-webview'.
> Could not initialize class org.jetbrains.kotlin.gradle.plugin.sources.DefaultKotlinSourceSetKt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.0/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 4m 24s

**Environment:**
 - OS: Android
 - OS version: -
 - react-native version: 0.61.4
- react-native-webview version: 7.4.3

**Comment by bstillitano** [comment] 2019-11-12 02:40
Getting same version after updating to the latest eap

**Comment by ShotSkydiver** [comment] 2019-11-21 18:32
Still an issue; the fix for this is to bump up the `ReactNativeWebView_kotlinVersion` to 1.3.50 or higher.

**Closed** 2019-11-26 09:41 UTC
Labels: Type: bug report

**Comment by id13** [comment] 2020-06-02 12:36
> Still an issue; the fix for this is to bump up the `ReactNativeWebView_kotlinVersion` to 1.3.50 or higher.

This comment is underrated.
Even with version 10.2.3 it was this bump up that fixed the build crash caused by this library.

**Comment by joshuapinter** [comment] 2020-06-17 22:18
For those stuck on React Native < 0.60.0 (i.e. pre-AndroidX) we've created a fork of `react-native-webview` version 5.8.2 with just the `ReactNativeWebView_kotlinVersion` bumped to 1.3.50. You can find it here: 

https://github.com/cntral/react-native-webview/tree/5_8_2

And you can include it in your `package.json` with this: 

```json
"react-native-webview": "github:cntral/react-native-webview#5_8_2"
```

In this branch we have precompiled all the TypeScript to JavaScript to make it easy to consume as well.

This works great for us, hopefully it helps others.

Thank you @ShotSkydiver for pin pointing the exact issue.

**Comment by Benzer1406** [comment] 2020-06-24 22:37
Still happening with version `10.3.1`

**Comment by javierbustamante** [comment] 2020-08-04 10:17
And still happening with version 10.3.3.
I solved it setting the version of kotlinVersion to the lastest one:
    buildscript {
        ext {
            kotlinVersion = '1.3.72'
        }
    }

**Comment by loopbender** [comment] 2020-08-19 15:41
> And still happening with version 10.3.3.
> I solved it setting the version of kotlinVersion to the lastest one:
> `buildscript { ext { kotlinVersion = '1.3.72' } }`

this saved my day muchos gracias
