### ISSUE TITLE
Invariant Violation: requireNativeComponent: "RNCWebView" was not found in the UIManager.

### ISSUE THREAD

**Issue by jason102** [react-native-community/react-native-webview#140] opened 2018-11-16 10:31 UTC
Hi all, I'm new to React Native and I'm getting the error in the title. 

Perhaps this is related to another previous post made 1 month ago:
" Invariant Violation: Native component for "RNCWKWebView does not exist"  "

**Comment by jason102** [comment] 2018-11-16 10:32
I'm using Expo as well. Are they the same issue? If it is, how do I use the new webview component without Expo?

**Comment by jason102** [comment] 2018-11-16 10:43
If I can't use Expo with this component, maybe I can just go ahead and use the old webview component assuming that Expo will eventually support it and then later switch to this one before RN removes the old one? I really would prefer not to have to do all the complicated Android Studio/Xcode setup work. I have Expo working just fine for everything else and think it's quite convenient....

**Comment by lunarraid** [comment] 2018-11-16 21:30
I am not using expo and am running into this.

**Comment by jamonholmgren** [comment] 2018-11-19 01:36
Hey folks, you won't be able to use this with Expo [unless you eject](https://docs.expo.io/versions/latest/expokit/eject).

If you are not using Expo or you have already ejected and you're still getting this issue, it may be because you forgot to run `react-native link react-native-webview`.

If you're still having trouble, feel free to file another issue or update this one. Thanks!

**Comment by lunarraid** [comment] 2018-11-19 01:57
Closing the issue on the assumption that we're simply not following instructions is a bit premature. As I stated, I am not using Expo, and as I am capable of both understanding and following instructions, I did indeed run `react-native link react-native webview`. The link command stated it was successful, but failed to link the binaries to the project, which I had to do manually to make this work.

**Comment by jamonholmgren** [comment] 2018-11-19 03:18
@lunarraid Apologies, did not intend to insinuate you're not following instructions. I closed the issue because the OP is using Expo and thus this particular issue is not relevant to your issue despite the similar error message.

If you can provide a minimal reproduction of this problem please do file a new issue.

**Comment by Titozzz** [comment] 2018-11-20 00:39
@lunarraid I'm indeed interested in understanding what went wrong so please open an issue if you can provide a reproduction.

**Comment by lunarraid** [comment] 2018-11-20 01:04
If I can find some time I'll see if I can reproduce it in a blank project. If it helps, my project is using pods, and the initial install link failed. I was able to get the link step to not fail by adding the `# Add new pods below this line` comment to my podfile, but even with the link 'succeeding' and the podfile addition, the library code was still not found at runtime. I had to remove the podfile entry and link it manually by adding the project and linking with the binary in Build Phases before it would work.

**Comment by Titozzz** [comment] 2018-11-20 07:41
Ok, are you linking react with the pods or manually ?

**Closed by Titozzz** 2018-11-20 07:41 UTC

**Comment by AndreevskiAleksandar** [comment] 2018-11-20 14:31
Same thing is happening here. I have ejected the project from expo, did the `react-native link react-native-webview` and I get the "Invariant Violation: requireNativeComponent: "RNCWebView" was not found in the UIManager." error. Reverting to the old webview until this is fixed.

**Comment by Titozzz** [comment] 2018-11-20 14:38
Are you using cocoapods @AndreevskiAleksandar ?

**Comment by Titozzz** [comment] 2018-11-20 14:49
Wait a minute RNCWebView does not exists, it's either RNCUIWebView or RNCWKWebView. There must be a bug 🤔

**Comment by lunarraid** [comment] 2018-11-20 17:14
@Titozzz I have entries in my podfile for the react code, since `react-native-webview` refuses to build without them. They look like this:
```
  rn_path = '../node_modules/react-native'

  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga"
  pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"
```

Annoyingly enough, I cannot reproduce this on a fresh project, though getting CocoaPods in general to work with react native (even on a fresh install) is such a pain in the rear. At the very least, using 
```
# Add new pods below this line
```
was a requirement to get this working properly. Since I was unable to repro on a fresh project, I am going to assume that there is some library conflict or version issue that made the link step fail, and just keep my current manual link fix for my project. Feel free to hit me up if you have any more questions.

**Comment by Titozzz** [comment] 2018-11-21 08:39
That is weird given that I have nearly the same podfile 🤔

**Comment by AndreevskiAleksandar** [comment] 2018-11-21 16:19
@Titozzz no, I am not using CocoaPods.. Its a direct eject from Expo, without any tinkering around with that (just followed the basic docs). After that I just linked it and made sure all the dependencies are in the gradle and settings file (I tested it for Android only). I ll take a look again at this in a few days..

**Comment by Titozzz** [comment] 2018-11-22 09:54
So I did : 
react-native init test
yarn add react-native-webview
react-native link react-native-webview

and everythings work without cocoapods.

On my project I use cocoapods without issues too.

**Comment by bruteforcecat** [comment] 2018-11-22 14:14
I have this problem for android only . trying to troubleshoot

**Comment by jamonholmgren** [comment] 2018-11-23 20:55
I tried spinning up a bare Expo app and ejecting immediately with ExpoKit, but got this error:

<details>
  <summary>`Task 'installDebug' not found in root project 'android'.`</summary>
```
> Configure project :app 
Could not find google-services.json while looking in [src/prod/min/sdk/dev/kernel/debug, src/prod/min/sdk/dev/debug, src/prod/min/sdk/dev/kernel, src/prod/min/sdk/dev/kernelDebug, src/prod/min/sdk/debug, src/prod/min/sdk/dev, src/prod/min/sdk/devDebug, src/prod/min/debug, src/prod/min/sdk, src/prod/min/sdkDebug, src/prodMinSdkDevKernel/debug, src/debug/prodMinSdkDevKernel, src/prod/debug, src/prod/min, src/prod/minDebug, src/prodMinSdkDevKernel, src/debug, src/prodMinSdkDevKernelDebug, src/prod, src/prodDebug]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Could not find google-services.json while looking in [src/prod/min/sdk/dev/kernel/release, src/prod/min/sdk/dev/release, src/prod/min/sdk/dev/kernel, src/prod/min/sdk/dev/kernelRelease, src/prod/min/sdk/release, src/prod/min/sdk/dev, src/prod/min/sdk/devRelease, src/prod/min/release, src/prod/min/sdk, src/prod/min/sdkRelease, src/prodMinSdkDevKernel/release, src/release/prodMinSdkDevKernel, src/prod/release, src/prod/min, src/prod/minRelease, src/prodMinSdkDevKernel, src/release, src/prodMinSdkDevKernelRelease, src/prod, src/prodRelease]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Could not find google-services.json while looking in [src/prod/min/sdk/prod/kernel/debug, src/prod/min/sdk/prod/debug, src/prod/min/sdk/prod/kernel, src/prod/min/sdk/prod/kernelDebug, src/prod/min/sdk/debug, src/prod/min/sdk/prod, src/prod/min/sdk/prodDebug, src/prod/min/debug, src/prod/min/sdk, src/prod/min/sdkDebug, src/prodMinSdkProdKernel/debug, src/debug/prodMinSdkProdKernel, src/prod/debug, src/prod/min, src/prod/minDebug, src/prodMinSdkProdKernel, src/debug, src/prodMinSdkProdKernelDebug, src/prod, src/prodDebug]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Could not find google-services.json while looking in [src/prod/min/sdk/prod/kernel/release, src/prod/min/sdk/prod/release, src/prod/min/sdk/prod/kernel, src/prod/min/sdk/prod/kernelRelease, src/prod/min/sdk/release, src/prod/min/sdk/prod, src/prod/min/sdk/prodRelease, src/prod/min/release, src/prod/min/sdk, src/prod/min/sdkRelease, src/prodMinSdkProdKernel/release, src/release/prodMinSdkProdKernel, src/prod/release, src/prod/min, src/prod/minRelease, src/prodMinSdkProdKernel, src/release, src/prodMinSdkProdKernelRelease, src/prod, src/prodRelease]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Could not find google-services.json while looking in [src/dev/min/sdk/dev/kernel/debug, src/dev/min/sdk/dev/debug, src/dev/min/sdk/dev/kernel, src/dev/min/sdk/dev/kernelDebug, src/dev/min/sdk/debug, src/dev/min/sdk/dev, src/dev/min/sdk/devDebug, src/dev/min/debug, src/dev/min/sdk, src/dev/min/sdkDebug, src/devMinSdkDevKernel/debug, src/debug/devMinSdkDevKernel, src/dev/debug, src/dev/min, src/dev/minDebug, src/devMinSdkDevKernel, src/debug, src/devMinSdkDevKernelDebug, src/dev, src/devDebug]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Could not find google-services.json while looking in [src/dev/min/sdk/dev/kernel/release, src/dev/min/sdk/dev/release, src/dev/min/sdk/dev/kernel, src/dev/min/sdk/dev/kernelRelease, src/dev/min/sdk/release, src/dev/min/sdk/dev, src/dev/min/sdk/devRelease, src/dev/min/release, src/dev/min/sdk, src/dev/min/sdkRelease, src/devMinSdkDevKernel/release, src/release/devMinSdkDevKernel, src/dev/release, src/dev/min, src/dev/minRelease, src/devMinSdkDevKernel, src/release, src/devMinSdkDevKernelRelease, src/dev, src/devRelease]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Could not find google-services.json while looking in [src/dev/min/sdk/prod/kernel/debug, src/dev/min/sdk/prod/debug, src/dev/min/sdk/prod/kernel, src/dev/min/sdk/prod/kernelDebug, src/dev/min/sdk/debug, src/dev/min/sdk/prod, src/dev/min/sdk/prodDebug, src/dev/min/debug, src/dev/min/sdk, src/dev/min/sdkDebug, src/devMinSdkProdKernel/debug, src/debug/devMinSdkProdKernel, src/dev/debug, src/dev/min, src/dev/minDebug, src/devMinSdkProdKernel, src/debug, src/devMinSdkProdKernelDebug, src/dev, src/devDebug]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Could not find google-services.json while looking in [src/dev/min/sdk/prod/kernel/release, src/dev/min/sdk/prod/release, src/dev/min/sdk/prod/kernel, src/dev/min/sdk/prod/kernelRelease, src/dev/min/sdk/release, src/dev/min/sdk/prod, src/dev/min/sdk/prodRelease, src/dev/min/release, src/dev/min/sdk, src/dev/min/sdkRelease, src/devMinSdkProdKernel/release, src/release/devMinSdkProdKernel, src/dev/release, src/dev/min, src/dev/minRelease, src/devMinSdkProdKernel, src/release, src/devMinSdkProdKernelRelease, src/dev, src/devRelease]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)


FAILURE: Build failed with an exception.

* What went wrong:
Task 'installDebug' not found in root project 'android'.
```
<details>

So I'll wait for a repro to clone down first.

**Comment by levi-beers** [comment] 2018-11-28 17:41
Not using Expo, I still have the issue with Android even though my MainApplication.java is fixed and react-native-webview is linked.

**Comment by Titozzz** [comment] 2018-11-28 17:41
can you tell me more ?

**Comment by Shragenator** [comment] 2018-12-01 04:34
Experiencing this issue in ejected expo after a successful link (by running react-native link react-native-webview and then confirming that RNCWebViewPackage() is imported and linked in MainApplication.java as according to @Titozzz ).

For myself the error is: "Invariant Violation: Invariant Violation: Invariant Violation: Native component for "RNCWebView" does not exist
   
Going to investigate the source for the react-native-webview module to see if I can spot the problem.

**Comment by mog3n** [comment] 2018-12-01 05:45
How I got it to work with cocoapods:
I ran `react-native link react-native-webview`, which for some reason did not fully link the libraries. I got the error that all you guys are experiencing when recompiling the app after linking.

I went to manually link the library.
1. Drag the xcodeproj from node_modules/react-native-webview/ios/ into XCode my_app/Libraries
2. Under build phases -> link binary with libraries, add libRNCWebView.a
Here's my Podfile
`platform :ios, '9.0'

target 'spark' do

  # Pods for spark
  pod 'Firebase/Core', '~> 5.3.0'
  pod 'Firebase/Auth', '~> 5.3.0'
  # pod 'Firebase/Database', '~> 5.3.0'
  # pod 'Firebase/Performance', '~> 5.3.0'
  pod 'Firebase/Messaging', '~> 5.3.0'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

end`
This seemed to work for me. Hope this helps any noobies such as myself.

**Comment by lunarraid** [comment] 2018-12-01 05:49
@mog3n You will likely need to remove the pod reference if you are linking under build phases. It didn't trigger for me, but this caused duplicate symbol errors for other people pulling down my project afterwards. Removing the pod reference fixed it for everyone.

**Comment by Sbphillips19** [comment] 2018-12-07 04:10
Mine works in IOS but I haven't been able to get it to work in android.  I have already followed everything above and see these in my MainApplication file:

import com.reactnativecommunity.webview.RNCWebViewPackage;
new RNCWebViewPackage()

Not really sure what else to try.  Have trying rebuilding and linking many times.

**Comment by MrOggy85** [comment] 2018-12-13 08:09
I ran into the same issue as the original comment ☝️ 
I am using React Native `0.55.2` and Xcode 10.

I was building with the iOS Simulator (iPad 5th gen) as the build target. And got the error. When I instead switch to "Generic iOS Device" it worked.

**Comment by renishdeveloper** [comment] 2019-01-08 05:52
Invariant Violation: requireNativeComponent: "RNCWebView" was not found in the UIManager
Not getting thr solution for this.

**Comment by Titozzz** [comment] 2019-01-08 09:53
For iOS and cocoapods, I wrote an article on how to properly and easily setup if you guys want : https://engineering.brigad.co/demystifying-react-native-modules-linking-ae6c017a6b4a.

**Comment by tjengland** [comment] 2019-01-08 21:17
Received this error today, resolved by simply adding the following line to Podfile:
  ```
pod 'react-native-webview', :path => '../node_modules/react-native-webview'
```
then:
```bash
cd ios/ && pod install && react-native run-ios --simulator=\"iPhone X\"
```

**Comment by timraybould** [comment] 2019-01-09 13:49
I was also getting this error on 0.57.8. Not using Expo. I _am_ using RNFirebase, which I suspect might be a common theme.

It might not be an issue of react-native-webview. Running `react-native link` almost never works for me and I have to resort to manually linking everything via Xcode. However, it might be nice for the project to include manual install instructions (which really aren't _that_ bad) for those of us that run into this.

To fix this, I used the manual install instructions from another package as a guide (https://github.com/transistorsoft/react-native-background-fetch/blob/master/docs/INSTALL-MANUAL-IOS.md). Specifically, only those first 2 steps were necessary:

1. Add `node_modules/react-native-webview/ios/RNCWebView.xcodeproj` to the Libraries folder (i.e. ProjectName > Libraries)

2. Go to Build Phases then "Link Binary with Libraries" then click the plus button and find / add `libRNCWebview.a`.

After that, rm -rf ios/build then react-native run-ios got it working for me.

**Comment by Titozzz** [comment] 2019-01-09 14:03
cf https://github.com/react-native-community/react-native-webview/issues/235#issuecomment-452382921 😄 . I'll add that to the docs hopefully soon

**Comment by Titozzz** [comment] 2019-01-31 15:35
https://github.com/react-native-community/react-native-webview/blob/master/docs/Getting-Started.md#2-link-native-dependencies has been updated

**Comment by marexv** [comment] 2019-02-10 21:19
Hi! Will we ever be able to use this with expo? :)

**Comment by Titozzz** [comment] 2019-02-11 09:57
Once expo decides to pull this code inside their new version yes, but the work has to be done on their side

**Comment by MSSPL-PiyaleeMaiti** [comment] 2019-03-12 06:39
@Titozzz you should add manual liking documentation in package document. It will help to developer to recheck manually that is it linking properly or not. I am facing the problem, and find the solution from here.
Thanks for solution.

**Comment by Titozzz** [comment] 2019-03-14 08:35
There is a linking section in the readme :disappointed:

**Comment by rpuls** [comment] 2019-03-20 12:20
Not sure this will help anyone. But i was having this issue as well, (just react native NO expo). I tried manully adding `import com.reactnativecommunity.webview.RNCWebViewPackage;` in MainApplication.java
Didn't do the trick. But decided to run `react-native unlink react-native-webview` and i noticed that it removed the import com.reactnativecommunity.webview.RNCWebViewPackage; which i manually added. After then again running `react-native link react-native-webview` I saw that it was this time added to the MainAplication.java, and the error was gone.

**Comment by MSSPL-PiyaleeMaiti** [comment] 2019-03-20 12:58
> There is a linking section in the readme

@Titozzz There is react-native-link for automatic linking. But there should be explain about manual linking. In our project automatic linking not working always(in Android), so I was needed the manual linking in MainApplication.java. That's why I am telling. The manual linking should be in readme.

**Comment by Titozzz** [comment] 2019-03-20 13:58
@MSSPL-PiyaleeMaiti https://github.com/react-native-community/react-native-webview/blob/master/docs/Getting-Started.md#2-link-native-dependencies

Did you see that part?

**Comment by MSSPL-PiyaleeMaiti** [comment] 2019-03-20 14:05
> @MSSPL-PiyaleeMaiti https://github.com/react-native-community/react-native-webview/blob/master/docs/Getting-Started.md#2-link-native-dependencies
> 
> Did you see that part?

No, not seeing this part. Sorry. :upside_down_face: it's my mistake.

**Comment by Titozzz** [comment] 2019-03-20 14:06
What should we update so that everyone sees it?

**Comment by MSSPL-PiyaleeMaiti** [comment] 2019-03-20 14:09
You can update the brief details in readme instead of article link, then
give article link to follow details.

Piyalee Maiti
Thanks & Regards

**Comment by xrareselX** [comment] 2019-04-22 13:58
@Titozzz 
I read this issue and these 2 
[https://github.com/react-native-community/react-native-webview/blob/master/docs/Getting-Started.md](url)
[https://engineering.brigad.co/demystifying-react-native-modules-linking-964399ec731b](url)
but when I use the link command, nothing shows, so I tried the manual linking but I do not have the files and folders that you mention in that article. For example, I don't find the settings.gradle file

**Comment by bohehe** [comment] 2019-08-06 09:55
this issue worked for me : [add react to target list](https://stackoverflow.com/questions/43311439/react-native-bvlineargradient-react-rctviewmanager-h-file-not-found?rq=1)

**Comment by waqaramjad** [comment] 2019-09-14 02:51
same issue in expo

**Comment by TommyLeong** [comment] 2019-10-07 02:20
I was facing the similar issue ```Invariant Violation: requireNativeComponent:xxx not found in UIManager```

Issue seems to be the dependent is not linked to your project, hence 2 solutions for this issue (depending on your 'dependency')

1. run ```react-native link``` in terminal/cmd at your project path. 
2. Manual append the dependency in your MainApplication.java as shown below:

```
@Override
    protected List<ReactPackage> getPackages() {      

      @SuppressWarnings("UnnecessaryLocalVariable")
      List<ReactPackage> packages = new PackageList(this).getPackages();
      // Packages that cannot be autolinked yet can be added manually here, for 
      packages.add(new RNFirebaseAnalyticsPackage());
      packages.add(new xxxPackage());
    }
```

**Comment by dennisclementino** [comment] 2019-10-18 02:11
After trying so hard to make it

yarn add react-native-webview

react-native link react-native-webview,

cd ios && pod install && cd ..

**Comment by TommyLeong** [comment] 2019-10-18 02:50
@dennisclementino Do your podfile has the following line?
`pod 'react-native-webview', :path => '../node_modules/react-native-webview'`

**Comment by luatnd** [comment] 2020-01-09 03:42
I'm facing a similar issue:
> Invariant Violation: requireNativeComponent: "**RNCUIWebView**" was not found in the UIManager.
react-native@0.61.x
react-native-webview@8.0.3
I'm using auto-link

**Comment by itolegmysin** [comment] 2020-01-14 13:55
> I'm facing a similar issue:
> 
> > Invariant Violation: requireNativeComponent: "**RNCUIWebView**" was not found in the UIManager.
> 
> [react-native@0.61.x](mailto:react-native@0.61.x)
> react-native-webview@8.0.3
> 
> I'm using auto-link

Hey, I'm facing a similar issue as well, following manual linking steps help me at least: 

1. **android/settings.gradle**:
`
include ':react-native-webview'
project(':react-native-webview').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-webview/android')
...`
2. **android/app/build.gradle**:
`
dependencies {
    implementation project(':react-native-webview')
    ....
`
3. **MainApplication.java**:
```
import com.reactnativecommunity.webview.RNCWebViewPackage;
....

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
          new RNCWebViewPackage(),
          ....
```
4. **ios/Podfile.**
```
...
  pod 'react-native-webview', :path => '../node_modules/react-native-webview'
...
```
5. **react-native.config.js** (I'm using 0.61.5 version of react-native):
```
....
'react-native-webview': {
      platforms: {
        android: null, // disable Android platform, other platforms will still autolink if provided
      },
    },
```

**Comment by LusineGasparyan98** [comment] 2020-01-15 11:20
@itolegmysin I have tried the same as you did without changing react-native-config.js file and it succeeded. I think if you undo that file, it will work

**Comment by Ericnsamba** [comment] 2020-03-09 06:15
Clean your build file, this worked for me.
if you're using xcode, **In Xcode navigate to:** 
Product > scroll down to _Clean_ > Press and hold _Option ⌥_ then click on _clean_

**Comment by tresf** [comment] 2020-03-11 21:16
I'm documenting how I got to this failure here in hopes to identify why this message occurs.

Platform: MacOS 10.15 Catalina, Android Studio 3.6.1, Nexus 5X API 29 x86

From the [Getting Started](https://reactnative.dev/docs/getting-started.html) guide... 
* Started following the Expo guide.
   * When I realized it required a special app to run, stopped, deleted the project.
* Starting following the React Native guide.
   * I had already had Android Studio installed and working with another Hello World (written in Java) so some steps were skipped.  The one missing step was adding the **Android SDK Command Line Tools** which was skipped on initial install.
* Got the React Native example running.

Next, I started using the [LogRocket tutorial](https://blog.logrocket.com/the-complete-guide-to-react-native-webview/) for setting up the WebView component.
* Without `yarn`, I followed the `npm` steps
* I had misread the linking step... 
   > "From react-native 0.60, auto-linking will handle the linking process, but don’t forget to run pod install."
   * I'm not using pods, and I didn't know if this meant auto-linking was going to handle this.  I tried the command but it failed on `zsh`, which is the recommended shell for macOS 10.15.
   * Knowing that tools might be coded for `bash`, I switched to `bash`, ran the command: `react-native link react-native-webview`.  It said it was successful.
* The error `Invariant Violation: requireNativeComponent: "RNCWebView" was not found in the UIManager.` still persists, so I read each recommendation and comment here.
* Per above recommendations I followed the guide [**Demystifying react-native modules linking**](https://engineering.brigad.co/demystifying-react-native-modules-linking-964399ec731b) to no avail.  I noticed the article recommends a change to `getPackages()`, but it didn't seem to work, the same error persists.

I'm sure something above involves an out-of-place step or wrongly followed instructions, but due to the number of people affected by this, I feel there's something awry that's easy to stumble upon, or common steps to make mistake on.

Note, I didn't know how to follow the XCode steps since I'm not using that as an IDE.

**Comment by tresf** [comment] 2020-03-11 21:46
Update to the above... 
* Started over with React Native Guide using `bash` (probably not relevant)
* Installed Android 28 (a step I had skipped over because Android Studio was already installed)
   * Android Studio -> Preferences -> Appearance and Behavior -> System Settings -> Android SDK -> Android 9.0 (Pie) 28
* Created new project under new name (probably not relevant)
* Followed the LogRocket tutorial

... and now it works.  Would the Android SDK cause this error?  If so, why didn't it occur when running a vanilla React Native app?

**Comment by tophernuts** [comment] 2020-04-01 22:19
So I was running into this similar issue on android while converting an existing android app into a react native one, and my good friend @Afroholic78 realized that within the `onCreate` of our ReactNative activity, we need to add the package there as well!

```
mReactInstanceManager = ReactInstanceManager.builder()
                .setApplication(getApplication())
                .setCurrentActivity(this)
                .setBundleAssetName("index.android.bundle")
                .setJSMainModulePath("index")
                .addPackage(new MainReactPackage())
                .addPackage(new RNCWebViewPackage()) // this saved our lives
                .setUseDeveloperSupport(BuildConfig.DEBUG)
                .setInitialLifecycleState(LifecycleState.RESUMED)
                .build();
``` 

I wasn't able to see this documented anywhere, but this is seemingly the only thing that fixed it for us!

**Comment by JakinTayo** [comment] 2020-04-30 19:04
![image](https://user-images.githubusercontent.com/46313179/80748832-787d2000-8b1d-11ea-9854-347e67b6758e.png)
This library has frustrated me I have done everything. Please help with this library or help with alternative libraries. Please.

**Comment by sebgam** [comment] 2020-05-02 04:47
> ![image](https://user-images.githubusercontent.com/46313179/80748832-787d2000-8b1d-11ea-9854-347e67b6758e.png)
> This library has frustrated me I have done everything. Please help with this library or help with alternative libraries. Please.

I have the same problem did you manage to solve it?

**Comment by akshay9** [comment] 2020-06-23 09:48
I was facing this same error, fixed it by re-running 
`npx react-native run-android`

**Comment by akshaypunchh** [comment] 2020-11-22 12:44
I think you did not link react-native-webview so link it first.
`react-native link react-native-webview
`
Just check the dependency added or not in your MainApplication class.

`import com.reactnativecommunity.webview.RNCWebViewPackage;
`
`new RNCWebViewPackage(),
`

**Comment by Majdi-Alkhusha** [comment] 2021-09-07 19:39
install react-native-screens work for me
`npm i react-native-screens`

**Comment by genialkartik** [comment] 2021-09-19 06:16
These steps worked for me:
1. Rebuild the App. Run: `npx react-native run-android`.
2. Run: `react-native link react-native-webview`
3. Check if `RNCWebViewPackage` is imported in `MainApplication.java` file.

Note: I'm using `react-native@0.64.2`.

**Comment by xMxster** [comment] 2022-01-19 20:34
Same for me guys, it started with react-native-math-view, since I couldn't use it I wanted to move to this as a fallback.

I DON'T THINK this is a webview problem itself, but a react one...

**Comment by muhammadasadullahtariq** [comment] 2022-03-02 19:17
Have you tried to link manually?

Go to ../node_modules/react-native-webview/ios and drag and drop the RNCWebView.xcodeproj to Libraries folder on Xcode, right after, Go to Build Phases tab (on Xcode) in the section "Link binary With libraries" add the libRNCWebView.a (inside Libraries/RNCWebView.xcodeproj/Products). Try to build and run

**Comment by cancmgz** [comment] 2022-03-30 19:12
There is nothing left that I haven't tried for hours.
"**react-native link -react-native-webview**",
I ran "**react-native link**".
"**pod install**" in ios folder.

restart project, restart macos, i try everything.

but I still get the error "RNCWebView does not exist".

**Comment by iboxgithub** [comment] 2022-03-31 13:21
same here

**Comment by MaxJadav** [comment] 2022-07-27 11:14
Getting crash after generating aab file "react-native-webview": "^11.22.3"
Fatal Exception: com.facebook.react.common.JavascriptException: Invariant Violation: requireNativeComponent: "RNCWebView" was not found in the UIManager.

When run app as release mode working fine.
After generating aab file. Download from internal testing.
![Screenshot 2022-07-27 at 4 42 35 PM](https://user-images.githubusercontent.com/31030098/181233780-eb9e2f02-c853-437f-a9d2-498bbdc91dde.png)

**Comment by aiya000** [comment] 2024-07-11 16:05
I had a same issue.
Below step fixes the issue.

```diff
-    "react-native-webview": "^13.10.5"
+    "react-native-webview": "^13.8.6"
```

**Comment by Be-Que** [comment] 2024-07-13 18:46
Run this on your terminal and reload the project
npx expo install react-native-webview
This worked for me!
