### ISSUE TITLE
Performance worse than browser: Is caching the problem?

### ISSUE THREAD

**Issue by jkustan** [react-native-community/react-native-webview#128] opened 2018-11-06 07:44 UTC
I am using react-native-webview to navigate to a site, and it is taking noticeably more time than it does in the native browser. The problem is worse on Android than on iOS.

* Is this a known problem with a known solution that I'm missing somehow?
* Is the caching the problem? When I go to a site and then return in Safari, it loads instantly, but the webview always takes the same 5-10 seconds to load.
* Is there a way to enable progressive loading? It doesn't seem to render until the entire DOM and javascript is finished, which seems more like the way browsers loaded things back in the 1990s than today.
* Is there a way to share the cache between webview instances in the same app?

It seems to me that I should be able to go to our (angularjs-based) single page app, pay the penalty once to download all the js, and from then on any webview that goes to that site should just have to download the html, for more or less instant performance. Instead it always takes 5-10 seconds or more, each time like the first time. Ditto for going to regular sites (eg news sites) that always behave as if caching is turned off and take much longer to load than in the mobile browser.

Hoping I'm missing something simple here -- or that someone has an idea for a coded workaround.

Many thanks!

Jack

**Comment by jamonholmgren** [comment] 2018-11-07 18:02
Hey @jkustan, I'm not sure what the issue might be. I did see a reference to `suppressesIncrementalRendering` [here](https://stackoverflow.com/a/49793817/204044). You can hook it up to Mac Safari dev tools to do some debugging -- see here: https://github.com/react-native-community/react-native-webview/blob/master/docs/Debugging.md.

**Comment by jkustan** [comment] 2018-11-07 23:10
Thanks @jamonholmgren. How would I set the suppressesIncrementalRendering flag? Although it looks like suppress is false by default.

No matter how many times the webview loads, it always takes the same time. It seems clear that nothing is being cached. Does no one else have this issue? I can try the debugger as well...

**Comment by jkustan** [comment] 2018-11-08 08:19
I did try debugging (thanks for the tip) but since I'm trying to record load times it's not really helpful. Once the page loads I can attach to it and debug, but I can't get load times since by the time I see it in the Safari debug menu it's already loaded.

Any other thoughts / ideas?

**Comment by jkustan** [comment] 2018-11-08 10:09
I turned off the startInLoadingState in the hopes that it would show sooner. But it still seems to be waiting until the entire page is loaded until it goes from blank to fully rendered (with no intermediate / progressive load), and it also doesn't seem to be caching anything. Things are much faster (and cached) in safari.

**Comment by bruteforcecat** [comment] 2018-11-15 10:42
It seems the caching for webview is not working. and the interesting thing is the httpCache size keep increasing even for the same url. I added the beblow code inside `visitSource`
```
  NSURLCache *httpCache = [NSURLCache sharedURLCache];
  printf("currentDiskUsage : %d", (int)[httpCache currentDiskUsage]);
```

**Comment by Salakar** [comment] 2018-11-19 02:35
As far as I can tell, on iOS, `WKWebViewConfiguration` should be set with a `WKWebsiteDataStore` instance for caching to work, can't see it being set anywhere though in the code base?

Can someone try adding the following after this line and try it out; https://github.com/react-native-community/react-native-webview/blob/master/ios/RNCWKWebView.m#L87

```objc
wkWebViewConfig.websiteDataStore = [WKWebsiteDataStore allWebsiteDataTypes];
```

References:
https://developer.apple.com/documentation/webkit/wkwebviewconfiguration/1395661-websitedatastore?language=objc
https://developer.apple.com/documentation/webkit/wkwebsitedatastore?language=objc

**Comment by jamonholmgren** [comment] 2018-11-19 02:58
I get this when I do that:

![image](https://user-images.githubusercontent.com/1479215/48683836-dd2fff00-eb63-11e8-9478-6b238bf6da15.png)

**Comment by jamonholmgren** [comment] 2018-11-19 03:03
I don't think `allWebsiteDataTypes` is what we want ... I'm trying to figure out what we _do_ want, though.

**Comment by jamonholmgren** [comment] 2018-11-19 03:06
So doing this works great:

```objective-c
    wkWebViewConfig.websiteDataStore = [WKWebsiteDataStore defaultDataStore];
```

**Comment by jamonholmgren** [comment] 2018-11-19 03:16
I can confirm that adding the above line _does_ improve page loads immensely. Looks like @Salakar found the issue.

Will this conflict with #138 at all? I'm not familiar enough with process pools vs data stores to know.

**Comment by Salakar** [comment] 2018-11-19 08:51
> I don't think allWebsiteDataTypes is what we want ... I'm trying to figure out what we do want, though.

Sorry this was my bad, I did update my comment shortly after to indicate the correct change, the default datastore as you pointed out

**Comment by Titozzz** [comment] 2018-11-20 00:41
Can someone provide a PR ? This definitely should land on the repo

**Comment by Salakar** [comment] 2018-11-20 10:46
@Titozzz the reason I've not PR'd is I'm wondering if this should be configurable like all the other props, as it could, in theory, be a breaking change if we turn it on by default now.

**Comment by Titozzz** [comment] 2018-11-20 10:48
let's add a prop enableCache={true} by default ?

**Comment by Salakar** [comment] 2018-11-20 11:01
Ok will send a PR up shortly 👍

**Comment by Ehesp** [comment] 2019-04-03 22:06
Closing - please see the above PR for the `cacheEnabled` prop.

**Closed by Ehesp** 2019-04-03 22:06 UTC
Labels: User: question

**Comment by Liqiankun** [comment] 2020-09-24 13:57
`cacheEnable` really solved this issue?

**Comment by liudmyla-schastlyvets** [comment] 2020-12-17 18:59
@Liqiankun Did you find a way to improve WebView performance?

**Comment by Liqiankun** [comment] 2020-12-18 00:25
@liudmyla-schastlyvets  
```js
<WebView cacheEnabled={false} />
```
This works for me.

**Comment by billxie1988** [comment] 2021-02-04 06:51
try renderLoading={() => null}.this is a temporary method.I thought this is not the cache problem. the worse behavior is cause the renderLoading layer dismiss too late. RenderLoading layer dismiss relies on the webcore's didFinishLoad. But sometime the dom is finish render but some jscript async casue the webview finishLoad even later. RNWebview's renderLoading layer is always cover on the webview, so we feel it  performance worse.We need to do some thing on make the rendering layer dismiss early

<img width="235" alt="07bf9d61e3fa" src="https://user-images.githubusercontent.com/8359662/106855585-1f6b9980-66f8-11eb-9cca-8ea2dcc677e9.png">
