### ISSUE TITLE
Project stopped building after 5.0.7 error (requires kotlin?)

### ISSUE THREAD

**Issue by tapir** [react-native-community/react-native-webview#333] opened 2019-02-11 12:15 UTC
I've updated my working project to 5.0.7 and it doesn't build for android anymore
```
A problem occurred configuring project ':react-native-webview'.
> Could not resolve all artifacts for configuration ':react-native-webview:classpath'.
   > Could not find org.jetbrains.kotlin:kotlin-gradle-plugin:null.,
```

**Comment by tapir** [comment] 2019-02-11 12:29
To be precise it looks like whatever happened happened in 5.0.1. 5.0.0 works as it should but 5.0.1+ gives error above

**Comment by Titozzz** [comment] 2019-02-11 23:52
Closing as duplicate of #310

**Closed by Titozzz** 2019-02-11 23:52 UTC
