### ISSUE TITLE
No support for accessing setLoadWithOverviewMode on Android

### ISSUE THREAD

**Issue by jarredt** [react-native-community/react-native-webview#113] opened 2018-10-26 17:58 UTC
Android's native Webkit has a method `setLoadWithOverviewMode` ([documentation](https://developer.android.com/reference/android/webkit/WebSettings.html#setLoadWithOverviewMode(boolean))) that controls whether a webpage whose content exceeds the window width will be scaled out to fit all the content in the viewport when the page loads. It is defaulted to false. (The iOS implementation appears to be defaulted to true, based on how RN Webkit behaves on that platform).

There is not currently a prop exposed to control this setting in React Native's Webview component. Especially given the disparity in default behavior between Android/iOS, having this setting to reconcile the behavior would be very useful.

**Comment by TheAlmightyBob** [comment] 2018-10-30 16:22
Simply exposing `setLoadWithOverviewMode` directly as an Android-only property is probably the "easy" fix for this...

But `scalesPageToFit` should probably be considered as well. This maps to the inverse of Android's `setUseWideViewport`. What is the intended behavior of `scalesPageToFit` on Android? The behavior it _describes_ sounds very much like the behavior that is achieved by setting it to _false_ and enabling `setLoadWithOverviewMode`. It appears to be based on a UIWebView behavior that I'm not familiar with.

Does the current `scalesPageToFit` behavior have value of its own on Android? Would altering it be too much of a breaking change?

**Comment by Titozzz** [comment] 2018-10-30 16:29
@TheAlmightyBob The easy fix is not always the best, considering react-native, cause it would be painful to have duplicate props for everything 😛 . Which is why we always try to find a common interface when possible ! However this does not mean we do not implement platform specific props.

We can always do breaking changes as we use semver and if we document everything well it's ok.

**Comment by Nermin-K** [comment] 2019-01-07 12:22
@jarredt Could you please mention how to modify ReactWebViewManager.java file to make this solution work?! 
 I tried to modify [ReactWebViewManager.java](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/webview/ReactWebViewManager.java) file by adding this line `setting.setLoadWithOverviewMode(true);` inside `protected WebView createViewInstance` function and run command `react-native run-android start` but nothing changes.
I don't know if I'm doing it right or not! I'm just a beginner at React native and I have no previous experience with android or java.

**Comment by TheAlmightyBob** [comment] 2019-01-07 21:37
@Nermin-K The current workaround isn't to modify ReactWebViewManager.java directly, it's to subclass it in your project and put the change there. https://github.com/facebook/react-native-website/blob/master/docs/custom-webview-android.md outlines the process for subclassing the webview on Android (written before the webview was split out into this community project, but I assume it still works)

**Comment by Titozzz** [comment] 2019-01-08 09:33
on iOS with the WKWebview this is not possible either by the way

**Closed** 2019-02-28 21:02 UTC
Labels: enhancement
