### ISSUE TITLE
Error with latest version on Android (Crypto package not exist for RN)

### ISSUE THREAD

**Issue by sebinq** [react-native-community/react-native-webview#1312] opened 2020-04-10 06:22 UTC
So I keep getting following error:

<img width="497" alt="Screenshot 2020-04-10 at 08 20 32" src="https://user-images.githubusercontent.com/33039909/78968182-40795300-7b04-11ea-8ad2-c4b242b20c1f.png">

Which can be easily solved by adding `react-native-get-random-values` package and importing it from `index.js` of my project.

Thah being said, I don't think it's a good practive to let users deal with this kind of thing. Are UUID and node's crypto packages required to run webview? 

Thanks.

**Comment by LiDevil** [comment] 2020-04-10 06:23
same here

**Comment by sebinq** [comment] 2020-04-10 06:29
@LiDevil you can solve it for now by step described above.

**Comment by LiDevil** [comment] 2020-04-10 06:49
not working...can you tell me the solution detail? @sebinq 
i have installed the `react-native-get-random-values` in my proj , and add `import 'react-native-get-random-values';` in my index.js file and react-native-webview index.js file ，someting wrong?
my proj :
```
import {AppRegistry} from 'react-native';
import App from './App';
import {name as appName} from './app.json';
import 'react-native-get-random-values';

AppRegistry.registerComponent(appName, () => App);
```
webview proj:
```
import WebView from './lib/WebView';
import 'react-native-get-random-values'

export { WebView };
export default WebView;
```

**Comment by sebinq** [comment] 2020-04-10 06:51
Try to move import at very top of the index.js file

**Comment by sebinq** [comment] 2020-04-10 06:51
And make sure to run development server with `--reset-cache` flag

**Comment by LiDevil** [comment] 2020-04-10 06:54
thanks!! it working now!

**Comment by Sine99** [comment] 2020-04-10 21:54
Same issue here, I reverted back to v9.1.1 till this bug is fixed ...Not facing any issue so far.

**Comment by fungilation** [comment] 2020-04-10 21:58
Reproduced on RN webview 9.1.3 and RN 0.62.2, on both debug and release builds.

**Comment by fungilation** [comment] 2020-04-10 21:59
Reproduced on RN webview 9.1.3 and RN 0.62.2, on both debug and release builds.

Working around with
```
if (Platform.OS !== 'ios') require('react-native-get-random-values')
```

**Comment by Ding95** [comment] 2020-04-13 03:39
When I `yarn add react-native-get-random-values`, got a new problem, null is an object(evaluating 'RNGetRandomValues.getRandomBase64')
![image](https://user-images.githubusercontent.com/12723947/79089208-e84a8700-7d77-11ea-88de-fcb45a4b60e4.png)

As @Sine99 said, back to v9.1.1, everything are fine.

**Comment by ivan3177** [comment] 2020-04-13 07:55
Same thing for 9.14 and react-native 0.61.5

**Comment by nhinovaio** [comment] 2020-04-13 12:43
Find in node_modules/react-native-webview/lib/WebView.android.js
then add to line 61: 
import 'react-native-get-random-values';
import { v4 as uuidv4 } from 'uuid';

**Comment by dev20190101** [comment] 2020-04-14 08:00
> When I `yarn add react-native-get-random-values`, got a new problem, null is an object(evaluating 'RNGetRandomValues.getRandomBase64')
> ![image](https://user-images.githubusercontent.com/12723947/79089208-e84a8700-7d77-11ea-88de-fcb45a4b60e4.png)
> 
> As @Sine99 said, back to v9.1.1, everything are fine.

Same issue with the setup
    "react-native": "0.62.2",
    "react-native-get-random-values": "1.3.1",
    "react-native-webview": "9.2.0"

**Comment by mallipurna03** [comment] 2020-04-14 08:54
I followed same and did the modifications in my existing project, Please check the screen of the crash log following.
![Screenshot_20200414-141644](https://user-images.githubusercontent.com/13198787/79205193-3be1d100-7e5b-11ea-8a7e-3e0c6d410fc1.png)

And my package.json contains
"react-native-get-random-values": "^1.3.1",
"react-native-webview": "^9.0.2",
"uuid": "^7.0.3"

MapView.js contains following code
import 'react-native-get-random-values';
import { v4 as uuidv4 } from 'uuid';
import React, { memo, useState, Component, useEffect } from 'react';
import { TouchableOpacity, StyleSheet, ActivityIndicator, TouchableWithoutFeedback, Text, View, Alert, Dimensions, Picker, LayoutAnimation } from 'react-native';
import { WebView } from 'react-native-webview';


export const MapView = ({ route, navigation }) => {
  // uuidv4();
    return (
    <WebView
      source={{ uri: 'https://reactnative.dev/' }}
      style={{ marginTop: 20 }}
    />
  );
}

**Comment by DomiR** [comment] 2020-04-14 10:33
Instead of using uuid package we probably should use something like this:

```
// uuid.js
export function uuid() {
	let d = new Date().getTime();

	return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, c => {
		const r = (d + Math.random() * 16) % 16 | 0;
		d = Math.floor(d / 16);

		return (c === 'x' ? r : (r & 0x3) | 0x8).toString(16);
	});
}
```

@dev20190101 you probably forgot to rebuild (`react-native run-android`) as your error indicates, that the native module (couterpart to the js part of react-native-get-random-values) is not available yet. If you already did that, try `cd android && ./gradlew clean` first.

**Comment by mallipurna03** [comment] 2020-04-14 12:47
> Instead of using uuid package we probably should use something like this:
> 
> ```
> // uuid.js
> export function uuid() {
> 	let d = new Date().getTime();
> 
> 	return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, c => {
> 		const r = (d + Math.random() * 16) % 16 | 0;
> 		d = Math.floor(d / 16);
> 
> 		return (c === 'x' ? r : (r & 0x3) | 0x8).toString(16);
> 	});
> }
> ```
> 
> @dev20190101 you probably forgot to rebuild (`react-native run-android`) as your error indicates, that the native module (couterpart to the js part of react-native-get-random-values) is not available yet. If you already did that, try `cd android && ./gradlew clean` first.

@DomiR Thanks for the prompt response, I tried with your solution, seems not working, but i tried to generate debug apk and install it in mobile working fine..but only when i am and running and installing it from metro server it is not working. Any solution would be appreciate...

**Comment by davidepalazzo** [comment] 2020-04-14 20:07
@DomiR solution works. Use [patch-package](https://www.npmjs.com/package/patch-package) to persist the fix in the node_module folder while a fix is put in place. Not ideal but does the job for now.

**Comment by nasreekar** [comment] 2020-04-15 05:19
> Try to move import at very top of the index.js file

Which import? (react-native-webview ??)

**Comment by nasreekar** [comment] 2020-04-15 05:38
Doesn't work for me. I tried adding `react-native-get-random-values` using `npm install --save react-native-get-random-values` and I still see the same issue.

**Comment by ritesh-malav** [comment] 2020-04-15 15:35
![image](https://user-images.githubusercontent.com/4909388/79356574-c6f6c000-7f5c-11ea-9b14-527cf8c5d4d1.png)
Did the above step still this error persists.

**Comment by choonghee-lee** [comment] 2020-04-16 08:03
If you are using Expo, please "expo install react-native-webview" 👍

**Comment by ritesh-malav** [comment] 2020-04-16 08:37
No, I am not using expo. 

I am using pure react native with following versions:
`"react": "16.11.0",`
`"react-native": "0.62.1",`
`"react-native-webview": "^9.2.1"`

**Comment by choonghee-lee** [comment] 2020-04-16 08:43
@ritesh-malav 
I had the same issue, when I didn't install it by expo command.
before expo: "react-native-webview": "^9.2.1"
after expo:  "react-native-webview": "8.1.1"

maybe try 8.1.1 version !

**Comment by ritesh-malav** [comment] 2020-04-16 09:02
Downgraded the react-native-webview version to 8.1.1 after that it is showing following error message:

`<WebView source={{ uri: 'https://reactnative.dev/' }} />`

![image](https://user-images.githubusercontent.com/4909388/79436907-1980bc80-7fef-11ea-871e-bd5a6d7844df.png)

**Comment by choonghee-lee** [comment] 2020-04-16 09:06
@ritesh-malav 
hmm... I have no idea for the error. Here are all my dependencies that I'm currently working on.
`"dependencies": {
    "@expo/vector-icons": "^10.0.6",
    "@react-native-community/masked-view": "0.1.6",
    "@react-navigation/bottom-tabs": "^5.2.6",
    "@react-navigation/native": "^5.1.5",
    "@react-navigation/stack": "^5.2.10",
    "apollo-boost": "^0.4.7",
    "expo": "~37.0.3",
    "graphql": "^15.0.0",
    "react": "~16.9.0",
    "react-apollo": "^3.1.5",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz",
    "react-native-gesture-handler": "~1.6.0",
    "react-native-reanimated": "~1.7.0",
    "react-native-safe-area-context": "0.7.3",
    "react-native-screens": "~2.2.0",
    "react-native-showdown": "^1.0.1",
    "react-native-svg": "^12.1.0",
    "react-native-web": "~0.11.7",
    "react-native-webview": "8.1.1",
    "react-redux": "^7.2.0",
    "redux": "^4.0.5",
    "styled-components": "^5.1.0"
  }`

**Comment by ritesh-malav** [comment] 2020-04-16 09:13
@choonghee-lee It's ok 😄. Feels good to have someone help here. I will keep on looking if I find anyting will post here.

**Comment by Ding95** [comment] 2020-04-16 09:30
> Downgraded the react-native-webview version to 8.1.1 after that it is showing following error message:
> 
> `<WebView source={{ uri: 'https://reactnative.dev/' }} />`
> 
> ![image](https://user-images.githubusercontent.com/4909388/79436907-1980bc80-7fef-11ea-871e-bd5a6d7844df.png)

reset cache, have a try.

**Comment by ritesh-malav** [comment] 2020-04-16 12:12
Yup it works.

**Comment by juhilsomaiya** [comment] 2020-04-17 08:35
It doesn't work in my case. 
Case 1: I've installed that package. https://www.npmjs.com/package/react-native-get-random-values
imported at the top of my index file. 
Case 2: downgraded webview to the 9.1.1 version because previously it was working in that version.

Now either of the solutions are not working. 
Is there anyone who found the solution ?

**Comment by tapz** [comment] 2020-04-17 10:08
For me it works when the import is in the first line of index.js and you rebuild everything:

rm -rf ~/.gradle/caches/
delete the Android build directory
restart Metro

**Comment by tapz** [comment] 2020-04-17 10:10
I just wonder why the new version was released when it does not work at all?

**Comment by gavrichards** [comment] 2020-04-17 12:31
> I just wonder why the new version was released when it does not work at all?

Agreed. I've had to roll back to 9.1.1 which seems to be the last working version that doesn't have this issue. If this package now requires a new package to be installed, it really should be explained in the setup instructions and the release notes.

**Comment by sibelius** [comment] 2020-04-17 13:01
@tapz we need automated tests to make sure it works well 

can you add thoses?

**Comment by sarthak216-blr** [comment] 2020-04-17 13:08
> For me it works when the import is in the first line of index.js and you rebuild everything:
> 
> rm -rf ~/.gradle/caches/
> delete the Android build directory
> restart Metro

Worked

**Comment by tapz** [comment] 2020-04-17 13:14
@sibelius I don't think anything should ever be published without first testing with a test app in a real device.

**Comment by sibelius** [comment] 2020-04-17 13:21
> I just wonder why the new version was released when it does not work at all?

I don't think your comment helps

**Comment by tapz** [comment] 2020-04-17 13:24
> I don't think your comment helps

A workaround to the bug is already here, so no help needed. But would be nice to ensure that this does not happen again.

**Comment by sibelius** [comment] 2020-04-17 13:45
add tests and this won't happen anymore

**Comment by tapz** [comment] 2020-04-17 13:52
Maybe I add tests to my app so I can avoid all non-tested dependencies.

**Comment by sibelius** [comment] 2020-04-17 13:54
why not add tests to the dependencies that you use?

**Comment by tapz** [comment] 2020-04-17 13:57
I don't blindly trust tests. I always test manually before releasing anything.

**Comment by gavrichards** [comment] 2020-04-17 13:57
> A workaround to the bug is already here, so no help needed.

A workaround buried in this issue thread is no use to people newly installing this package who then find it doesn't work out of the box. I thought it was a perfectly reasonable comment.

**Comment by curiousdustin** [comment] 2020-04-17 18:11
> Instead of using uuid package we probably should use something like this:
> 
> ```
> // uuid.js
> export function uuid() {
> 	let d = new Date().getTime();
> 
> 	return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, c => {
> 		const r = (d + Math.random() * 16) % 16 | 0;
> 		d = Math.floor(d / 16);
> 
> 		return (c === 'x' ? r : (r & 0x3) | 0x8).toString(16);
> 	});
> }
> ```
> 
> @dev20190101 you probably forgot to rebuild (`react-native run-android`) as your error indicates, that the native module (couterpart to the js part of react-native-get-random-values) is not available yet. If you already did that, try `cd android && ./gradlew clean` first.

This worked for me. I prefer creating a (hopefully temporary) patch over adding another module.

**Comment by temchannat** [comment] 2020-04-18 10:53
I had the same problem when I use **"react-native-webview": "9.2.1"**, but I change it to   **"react-native-webview": "9.0.2"** and it works fine.

**Comment by Jeepeng** [comment] 2020-04-18 19:26
#1301

**Comment by morganbigot** [comment] 2020-04-19 13:58
Hi, 
I followed the following: (adding react-native-get-random-values package and importing it from index.js of my project and from react-native-webview index.js at the top). I also cleared the cache, and now have that issue:
```
null is not an object (evaluating 'RNGetRandomValues.getRandomBase64')
* http://192.168.1.10:19001/node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false:124340:35 in getRandomValues
* [native code]:null in getRandomValues
* http://192.168.1.10:19001/node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false:157913:63 in v4
- node_modules/react-native-signature-canvas/node_modules/react-native-webview/lib/WebView.android.js:79:8 in WebView
```
Any idea to solve that?

**Comment by curiousdustin** [comment] 2020-04-19 14:12
Did you `pod install` in `iOS` directory?

**Comment by morganbigot** [comment] 2020-04-19 14:18
no it works on iOS, the error is on Android device

**Comment by curiousdustin** [comment] 2020-04-19 14:21
Oh. Right. Silly me. I got this confused with a different issue.

**Comment by morganbigot** [comment] 2020-04-19 20:28
Maybe the fact it doesn't work has something to do with Expo SDK 37? 

> Hi,
> I followed the following: (adding react-native-get-random-values package and importing it from index.js of my project and from react-native-webview index.js at the top). I also cleared the cache, and now have that issue:
> 
> ```
> null is not an object (evaluating 'RNGetRandomValues.getRandomBase64')
> * http://192.168.1.10:19001/node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false:124340:35 in getRandomValues
> * [native code]:null in getRandomValues
> * http://192.168.1.10:19001/node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false:157913:63 in v4
> - node_modules/react-native-signature-canvas/node_modules/react-native-webview/lib/WebView.android.js:79:8 in WebView
> ```
> 
> Any idea to solve that?

Maybe the fact it doesn't work has something to do with Expo SDK 37?

**Comment by jenshandersson** [comment] 2020-04-20 08:04
As mentioned above a temporary fix is to use patch-package. Thanks to @DomiR . Here is my patch that works fine: `patches/react-native-webview+9.2.1.patch`

```
diff --git a/node_modules/react-native-webview/lib/WebView.android.js b/node_modules/react-native-webview/lib/WebView.android.js
index 39a4e41..e452caf 100644
--- a/node_modules/react-native-webview/lib/WebView.android.js
+++ b/node_modules/react-native-webview/lib/WebView.android.js
@@ -59,12 +59,21 @@ var __rest = (this && this.__rest) || function (s, e) {
     return t;
 };
 import React from 'react';
-import { v4 as uuid } from 'uuid';
 import { Image, requireNativeComponent, UIManager as NotTypedUIManager, View, NativeModules, findNodeHandle, } from 'react-native';
 import BatchedBridge from 'react-native/Libraries/BatchedBridge/BatchedBridge';
 import invariant from 'invariant';
 import { defaultOriginWhitelist, createOnShouldStartLoadWithRequest, defaultRenderError, defaultRenderLoading, } from './WebViewShared';
 import styles from './WebView.styles';
+function uuid() {
+	let d = new Date().getTime();
+
+	return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, c => {
+		const r = (d + Math.random() * 16) % 16 | 0;
+		d = Math.floor(d / 16);
+
+		return (c === 'x' ? r : (r & 0x3) | 0x8).toString(16);
+	});
+}
 var UIManager = NotTypedUIManager;
 var RNCWebView = requireNativeComponent('RNCWebView');
 var resolveAssetSource = Image.resolveAssetSource;
```

**Comment by morganbigot** [comment] 2020-04-20 08:47
ok thank you i'll try that.

**Comment by alloy** [comment] 2020-04-20 11:50
Just driving by, but it seems to me that @DomiR’s solution could be made into a PR: https://github.com/react-native-community/react-native-webview/issues/1312#issuecomment-613359818. Is anybody that uses this package–which is not me at this moment–going to create a PR for it?

**Comment by artyorsh** [comment] 2020-04-20 16:10
I did https://github.com/react-native-community/react-native-webview/pull/1334 🙌

**Comment by mobeendev** [comment] 2020-04-21 09:11
> Reproduced on RN webview 9.1.3 and RN 0.62.2, on both debug and release builds.
> 
> And confirmed workaround with
> 
> ```
> import 'react-native-get-random-values'
> ```

Yes I also can also confirm on :

"dependencies": {
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-get-random-values": "^1.4.0",
    "react-native-webview": "^9.2.1"
  },

**Comment by mobeendev** [comment] 2020-04-21 09:12
I faced it on 

"dependencies": {
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-get-random-values": "^1.4.0",
    "react-native-webview": "^9.2.1"
  },

And fixed by 


/**
 * @format
 */
import 'react-native-get-random-values';   <<--------- adding this line
import {AppRegistry} from 'react-native';
import App from './App';
import {name as appName} from './app.json';

AppRegistry.registerComponent(appName, () => App);

**Comment by prostatus123** [comment] 2020-04-21 11:16
> When I `yarn add react-native-get-random-values`, got a new problem, null is an object(evaluating 'RNGetRandomValues.getRandomBase64')
> ![image](https://user-images.githubusercontent.com/12723947/79089208-e84a8700-7d77-11ea-88de-fcb45a4b60e4.png)
> 
> As @Sine99 said, back to v9.1.1, everything are fine.

help !

**Closed** 2020-04-21 14:41 UTC
Labels: Type: bug report

**Comment by alloy** [comment] 2020-04-21 15:08
Thanks @artyorsh!

**Comment by arif23decemeber** [comment] 2020-05-07 10:50
> not working...can you tell me the solution detail? @sebinq
> i have installed the `react-native-get-random-values` in my proj , and add `import 'react-native-get-random-values';` in my index.js file and react-native-webview index.js file ，someting wrong?
> my proj :
> 
> ```
> import {AppRegistry} from 'react-native';
> import App from './App';
> import {name as appName} from './app.json';
> import 'react-native-get-random-values';
> 
> AppRegistry.registerComponent(appName, () => App);
> ```
> 
> webview proj:
> 
> ```
> import WebView from './lib/WebView';
> import 'react-native-get-random-values'
> 
> export { WebView };
> export default WebView;
> ```

Work!!

**Comment by Nmncoded** [comment] 2024-10-07 15:02
import 'react-native-get-random-values';

Worked for me!!
Thankyou everyone
