### ISSUE TITLE
[Question] can file upload allow only camera, and not gallery?

### ISSUE THREAD

**Issue by Hamada92** [react-native-community/react-native-webview#762] opened 2019-08-07 01:31 UTC
Hi guys, 

thanks for the great plugin. 

I am wondering if file upload through webview can open only the camera, and disable the gallery option? 

Thanks

**Comment by andreipfeiffer** [comment] 2019-08-08 06:42
Duplicate of #378

The `capture` attribute is needed to support that, which is currently not implemented on Android.

**Closed** 2019-08-08 06:45 UTC
Labels: Type: feature request

**Comment by Hamada92** [comment] 2019-08-08 16:13
@andreipfeiffer if I work on this, would it suffice to have the chooser display only the camera option? or do we absolutely want to skip the chooser and go to the camera directly?

**Comment by andreipfeiffer** [comment] 2019-08-08 16:26
Well, it would be nice to mimic the behavior of a real browser, like here: http://anssiko.github.io/html-media-capture/

There are some steps to consider:
1. get the value of the `capture` attribute (surely it's not supported by older Android versions)
2. if there isn't an `accept` attribute, display the ActionsMenu without the File Explorer
3. is there is an `accept="image/*"` attribute, start the photo camera matched by the `capture` 
attribute (`user` - front, or `environment` - back ... if there are multiple cameras on device)
4. is there is an `accept="video/*"` attribute, start the video camera matched by the `capture` attribute (`user` - front, or `environment` - back ... if there are multiple cameras on device)

So, there are a lot of use cases. I would say that the code that starts the various camera apps is already there, there's only the issue of: getting the value of the `capture` attr and putting all the conditions in place.

I can help out if you want to tackle this.

**Comment by herujest** [comment] 2022-07-29 04:12
@IagoSilvaLima96 please help me, I need help to implement it

**Comment by narthanan24** [comment] 2023-02-20 02:50
@andreipfeiffer capture attribute implemented?

**Comment by andreipfeiffer** [comment] 2023-02-20 07:58
@narthanan24 I haven't touched this code since 2019, so I don't know the current status.
