### ISSUE TITLE
Execution failed in run-android

### ISSUE THREAD

**Issue by oihandover** [react-native-community/react-native-webview#582] opened 2019-05-19 18:22 UTC
**Bug description:**

I am run: 
$ yarn add react-native-webview
$ react-native link react-native-webview
$ react-native run-android

**To Reproduce:**

In run-android returns this: 

> Configure project :react-native-webview
:react-native-webview:reactNativeAndroidRoot /home/handover/Documents/handover/tests/paypalRN/node_modules/react-native/android

> Task :react-native-webview:compileDebugJavaWithJavac FAILED
/home/handover/Documents/handover/tests/paypalRN/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewFileProvider.java:3: error: package androidx.core.content does not exist
import androidx.core.content.FileProvider;
                            ^
/home/handover/Documents/handover/tests/paypalRN/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewFileProvider.java:10: error: cannot find symbol
public class RNCWebViewFileProvider extends FileProvider {
                                            ^
  symbol: class FileProvider
/home/handover/Documents/handover/tests/paypalRN/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewModule.java:14: error: cannot find symbol
import androidx.annotation.RequiresApi;
                          ^
  symbol:   class RequiresApi
  location: package androidx.annotation
/home/handover/Documents/handover/tests/paypalRN/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewModule.java:15: error: package androidx.core.content does not exist
import androidx.core.content.ContextCompat;
                            ^
/home/handover/Documents/handover/tests/paypalRN/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewModule.java:16: error: package androidx.core.content does not exist
import androidx.core.content.FileProvider;
                            ^
/home/handover/Documents/handover/tests/paypalRN/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewModule.java:178: error: cannot find symbol
  @RequiresApi(api = Build.VERSION_CODES.LOLLIPOP)
   ^
  symbol:   class RequiresApi
  location: class RNCWebViewModule
/home/handover/Documents/handover/tests/paypalRN/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewModule.java:224: error: cannot find symbol
    if (ContextCompat.checkSelfPermission(getCurrentActivity(), Manifest.permission.WRITE_EXTERNAL_STORAGE) != PackageManager.PERMISSION_GRANTED) {
        ^
  symbol:   variable ContextCompat
  location: class RNCWebViewModule
/home/handover/Documents/handover/tests/paypalRN/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewModule.java:352: error: cannot find symbol
    return FileProvider.getUriForFile(getReactApplicationContext(), packageName + ".fileprovider", capturedFile);
           ^
  symbol:   variable FileProvider
  location: class RNCWebViewModule
Note: /home/handover/Documents/handover/tests/paypalRN/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/handover/Documents/handover/tests/paypalRN/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
8 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-webview:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

**Environment:**
 - OS: Ubuntu
 - OS version: 18.4
 - react-native version: 16.8.3
 - react-native-webview version: 6.0.1

**Comment by Titozzz** [comment] 2019-05-19 21:47
Duplicate of #580

**Closed by Titozzz** 2019-05-19 21:47 UTC
Labels: Type: bug report

**Comment by Titozzz** [comment] 2019-05-19 22:50
Hello I fixed 6.0.2 and also released 5.9.1 if you don't want to upgrade!

**Comment by gentle-shao** [comment] 2019-07-09 07:58
Here's my solution : https://github.com/react-native-community/react-native-webview/issues/581#issuecomment-509534033

**Comment by rgallardo735** [comment] 2019-07-10 20:51
Thanks a lot!!!!, been stuck wit this error for days.

**Comment by BlackCod3** [comment] 2019-08-07 19:56
Hi, I'm facing the same pb but on **6.8.0**  :confused: 
@gentle-shao thanks for your contributions, but creating a new project is NOT a Solution

**Comment by rs4231199** [comment] 2020-03-08 04:35
@BlackCod3  If you have found any solution please share it.

**Comment by Winplaybox** [comment] 2020-05-31 20:14
Hello i fixed my solution for rnwebview
you can install  "react-native-webview": "^7.5.2", 
this will solve your solution in webview

**Comment by the-white-tiger** [comment] 2020-06-02 07:26
> Hello i fixed my solution for rnwebview
> you can install "react-native-webview": "^7.5.2",
> this will solve your solution in webview

This worked for me. Thanks Winplaybox
