### ISSUE TITLE
Hash character stops rendering on Android SDK 22.

### ISSUE THREAD

**Issue by export-mike** [react-native-community/react-native-webview#322] opened 2019-02-06 14:19 UTC
I'm using 
```
yarn list react-native react-native-webview
├─ react-native-webview@5.0.5
└─ react-native@0.58.3
```
whilst I cannot install this package on snack I've replicated the issue there using the core WebView.
https://snack.expo.io/HyHBdPO4E

I've also created an example project from react-native init.
https://github.com/export-mike/Android-22-Hash-Webview-Bug

Basically the Hash/Pound/Number Symbol whatever its called. Is stopping the webview from rendering any further elements.

In my example I'm replacing the symbol with the � symbol.

```js
import * as React from 'react';
import { Text, View, StyleSheet, Platform } from 'react-native';
import { WebView } from 'react-native-webview';
export default class WebViewExample extends React.PureComponent {
  render() {
    if (Platform.Version === 22) {
      return <WebView source={{
        html: `
      <html>
        <head>
          <meta charset="utf-8">
        </head>
        <body>
          Android Version: ${Platform.Version}
          <h1>Hello #NOF</h1>
          <h2>More Content</h2>
        </body>
      </html>`.replace(/#/g, '�')
      }} />
    }
    return <WebView source={{
      html: `
      <html>
        <head>
          <meta charset="utf-8">
        </head>
        <body>
          Android Version: ${Platform.Version}
          <h1>Hello #NOF</h1>
          <h2>More Content</h2>
        </body>
      </html>`}} />
  }
}
```

**Comment by MaximusHaximus** [comment] 2019-02-06 22:16
We're getting reports just starting this week from users impacted by this issue.

**Interestingly, we cannot reproduce this problem on all android devices, even on the same OS version.**

For example, my Galaxy S8 running Android 8.0 renders the content correctly, but another android device also running Android 8.0 is not rendering the content correctly.  For the same content, we're seeing 3 out of 5 devices not render it correctly.

**Comment by lukebaker** [comment] 2019-02-06 22:32
> We're getting reports just starting this week from users impacted by this issue.
> 
> **Interestingly, we cannot reproduce this problem on all android devices, even on the same OS version.**

This has been our experience as well.

**Comment by lukebaker** [comment] 2019-02-06 22:38
Ah, this appears to be a duplicate of this issue: https://github.com/react-native-community/react-native-webview/issues/298

**Comment by Titozzz** [comment] 2019-02-07 13:00
Closing in favor of #298

**Closed by Titozzz** 2019-02-07 13:00 UTC
