### ISSUE TITLE
Build fails for iOS on RN 0.57.0

### ISSUE THREAD

**Issue by maxammann** [react-native-community/react-native-webview#47] opened 2018-09-17 15:31 UTC
# What does not work correctly?
The build fails for me with this error:
```
/RCTUIWebViewManager.m -o /Users/integreat/integreat-react-native-app/ios/build/Build/Intermediates.noindex/RCTWebView.build/Debug-iphonesimulator/RCTWebView.build/Objects-normal/x86_64/RCTUIWebViewManager.o

/Users/integreat/integreat-react-native-app/node_modules/react-native-webview/ios/RCTUIWebViewManager.m:64:7: error: multiple methods named 'goForward' found with mismatched result, parameter type or attributes
      [view goForward];
      ^~~~~~~~~~~~~~~~
In module 'UIKit' imported from /Users/integreat/integreat-react-native-app/ios/build/Build/Products/Debug-iphonesimulator/include/React/RCTViewManager.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIWebView.h:56:1: note: one possibility
- (void)goForward;
^~~~~~~~~~~~~~~~~~
In module 'WebKit' imported from /Users/integreat/integreat-react-native-app/ios/build/Build/Products/Debug-iphonesimulator/include/React/RCTConvert.h:18:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk/System/Library/Frameworks/WebKit.framework/Headers/WKWebView.h:200:1: note: also found
- (nullable WKNavigation *)goForward;
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /Users/integreat/integreat-react-native-app/node_modules/react-native-webview/ios/RCTUIWebViewManager.m:6:
/Users/integreat/integreat-react-native-app/node_modules/react-native-webview/ios/RCTUIWebView.h:32:1: note: also found
- (void)goForward;
^~~~~~~~~~~~~~~~~~
1 error generated.



** BUILD FAILED **
```

# package.json
https://github.com/Integreat/integreat-react-native-app/blob/develop/package.json

# react-native info
```

  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i5-2400S CPU @ 2.50GHz
      Memory: 31.02 MB / 4.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.4 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 26.0.1, 26.0.3, 28.0.2
        API Levels: 26, 28
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.5.1 => 16.5.1 
      react-native: 0.57.0 => 0.57.0 

?  Done in 29.77s.
```

**Comment by Titozzz** [comment] 2018-09-18 12:50
Okay, I'm able to reproduce this and will fix ASAP

**Comment by Titozzz** [comment] 2018-09-18 12:57
I've pushed a fix onto master

**Closed** 2018-09-18 12:57 UTC
Labels: bug

**Comment by Titozzz** [comment] 2018-09-18 15:20
(Now the build fails due to #48
