### ISSUE TITLE
Question: Downloading files on android does not work

### ISSUE THREAD

**Issue by wendelfreitas** [react-native-community/react-native-webview#178] opened 2018-11-28 19:11 UTC
I do not know if I've forgotten anything, but no external link downloading file works. It comes in a loading and does not come out, is it possibly a bug or something I forgot?

Observation: '**allowUniversalAccessFromFileURLs**' is enabled

Thank's everyone! ❤️

**Comment by Titozzz** [comment] 2018-11-29 09:16
It's not a bug nor you forgot something. The feature has just never been done.
Upload was done just a few time ago.

There is already an issue, so I'll close this one #80 .

**Closed by Titozzz** 2018-11-29 09:16 UTC
