### ISSUE TITLE
WebView onNavigationStateChange url not updated

### ISSUE THREAD

**Issue by harryharihar** [react-native-community/react-native-webview#497] opened 2019-04-12 04:58 UTC
onNavigationStateChange = (navState) => {
    console.log(navState);
    if(navState.url===initialUrl.DOMAIN_URL){
      this.setState({
        canGoBack: navState.canGoBack,
        canGoForward: navState.canGoForward,
        changedUrl:false
      })
    }else{
      this.setState({
        canGoBack: navState.canGoBack,
        canGoForward: navState.canGoForward,
        changedUrl : true
  
      })
    }
    
  }

i have some custom logic to show and hide component on webview click below is my webview 
<WebView
              ref={webView => { this.refWeb = webView; }}
              style={{
                height:320,
                justifyContent: 'center',
                alignItems: 'center',

              }}
             scrollEnabled={true}
              //Loading URL
              source={
                {
                 
                  uri: initialUrl.DOMAIN_URL,
                  headers: {
                    Authorization: "Basic YmV0YTp2ZWVuYXdvcmxkMTIz",
                    client: "APP"
                  }
                }
              }
            
              javaScriptEnabled={true}
             domStorageEnabled={true}
             renderLoading={()=>this.DotIndicatorLoadingView()}
              injectedJavaScript={injectScript} 
              automaticallyAdjustContentInsets = {true}
              startInLoadingState={true}
              onNavigationStateChange={this.onNavigationStateChange} />

**Comment by Titozzz** [comment] 2019-04-15 08:25
Duplicate of #291

**Closed by Titozzz** 2019-04-15 08:25 UTC
