### ISSUE TITLE
Statusbar turns white when the webview is loaded on iOS 12

### ISSUE THREAD

**Issue by partiellkorrekt** [react-native-community/react-native-webview#735] opened 2019-07-22 13:38 UTC
**Bug description:**
PR #544 introduces a bug where the statusbar turns to UIStatusBarStyleLightContent (white text) when mounting a webview with a Youtube-video inside

**To Reproduce:**
- Turn the statusbar to default (dark text) using the react-native Statusbar-component
- Mount a webview with an embedded Youtube-video

**Expected behavior:**
Mounting a webview should not affect the statusbar

**Environment:**
 - OS: iOS
 - OS version: 12.2
 - react-native version: 0.60.4
 - react-native-webview version: 6.3.1

**What I can tell so far:**
- The following line (RNCWKWebView.m, line: 84) registers an event-handler that should only be called when entering/leaving fullscreen-mode:
```
[[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(toggleFullScreenVideoStatusBars) name:@"_MRMediaRemotePlayerSupportedCommandsDidChangeNotification" object:nil];
````
- Using NSlog-statements I can see that this event-handler is also called when the webview has finished loading
- This event-handler assumes the webview has just entered fullscreen and turns the statusbar to UIStatusBarStyleLightContent

**Comment by partiellkorrekt** [comment] 2019-07-22 13:43
As a Workaround adding `_isFullScreenVideoOpen = YES;` to `initWithFrame` in the same class fixes the behavior. But I think it would be better so see, why this event-handler gets called initially.

**Comment by jvandenaardweg** [comment] 2019-08-06 10:36
I'm experiencing the same thing, but without any youtube video embedded.

I've tracked this down to the use of a chat service called Drift. I've used a website from Drift's customer page to demonstrate the problem

```javascript
// This works fine, statusbar stays intact
<WebView
  ref={this.webviewRef}
  source={{ uri: 'https://www.google.com/' }}
  startInLoadingState={true}
  sharedCookiesEnabled={true}
  thirdPartyCookiesEnabled={true}
  useWebKit
  incognito={false}
  decelerationRate="normal"
/>
```

```javascript
// This makes the statusbar text to become white
<WebView
  ref={this.webviewRef}
  source={{ uri: 'https://www.lionbridge.com/' }}
  startInLoadingState={true}
  sharedCookiesEnabled={true}
  thirdPartyCookiesEnabled={true}
  useWebKit
  incognito={false}
  decelerationRate="normal"
/>
```

No YouTube embeds involved...

The only related "media" thing that seems to happen, is a download of a mp3 which plays when that Drift chat icon becomes active: https://js.driftt.com/deploy/assets/static/audio/52284660f7abf8538f64d3f7b857f505.mp3

Maybe that triggers the webview to think it is in fullscreen mode?

**Comment by partiellkorrekt** [comment] 2019-08-06 11:27
I am pretty shure that the notification "_MRMediaRemotePlayerSupportedCommandsDidChangeNotification" is the problem here as I can't find anything about it on the internet. Maybe there is a better way of determining when the webview enters/leaves fullscreen.

**Comment by redbluenat** [comment] 2019-08-12 12:46
I fixed it by setting in Info.plist

```
<key>UIViewControllerBasedStatusBarAppearance</key>
	<true/>
```

And in Xcode App->General-> Status Bar Style -> set to default :)

**Comment by partiellkorrekt** [comment] 2019-08-12 12:58
This fix doesn't work if you want to use react-native's StatusBar-component to change the statusbar-style. The StatusBar-component needs UIViewControllerBasedStatusBarAppearance to be false.

**Comment by redbluenat** [comment] 2019-08-12 13:01
aaa okay, I am using iOS default status bar and having the same issue so if sb needs the fix with the same situation it works for me.

**Comment by jvandenaardweg** [comment] 2019-08-12 14:54
For what it's worth to mention, using `5.8.0` temporary fixes the problem for me, as that's the version right before the `_MRMediaRemotePlayerSupportedCommandsDidChangeNotification` change mentioned by @partiellkorrekt

**Comment by redbluenat** [comment] 2019-08-19 14:10
@partiellkorrekt any updates about it? for RN 0.60 it is pretty annoying

**Comment by partiellkorrekt** [comment] 2019-08-20 07:40
@redbluenat I don't have any updates on that. I downgraded to 5.8.0 for now which in combination with jefifier works perfectly on the latest version of React-Native

**Comment by redbluenat** [comment] 2019-08-21 11:32
For me it isn't fix, I need the newest version and I have react native 0.60.4. I really need some info about this bug, it is pretty annoying for UX and UI. @Titozzz @jamonholmgren @MalcolmScruggs when do you think it will be fixed, it shouldn't take a lot of time if you know that in version 5.8.0 it is working perfectly.

**Comment by Titozzz** [comment] 2019-08-21 12:34
@redbluenat We are here to manage the repository and are not working full time on it, we will review PRs, try to help as much as we can but you cannot expect us to give you any ETA. Once again feel free to submit a PR 😃

**Comment by partiellkorrekt** [comment] 2019-09-25 12:45
I created a pull request that should fix this bug: https://github.com/react-native-community/react-native-webview/pull/898

**Comment by kesha-antonov** [comment] 2019-09-26 09:49
Hey!
IMO it should be really optional
I use WV to show some webpage and not in full screen. And status bar disappearing in header which is not expected behaviour

**Comment by partiellkorrekt** [comment] 2019-09-26 09:55
The patched code should not trigger as long as you don't enter fullscreen.

**Comment by kesha-antonov** [comment] 2019-09-26 10:29
Yeah
It's not related to your patch
Just saying that we should add new prop `autoManageStatusBar={false}` for people who want to manage StatusBar manually

**Comment by partiellkorrekt** [comment] 2019-09-26 11:21
If we add this property, I think we should also add the prop ```onFullscreenStateChange={(isFullscreen) => {}}``` or something like that.

**Comment by kesha-antonov** [comment] 2019-09-26 11:45
Why?

**Comment by partiellkorrekt** [comment] 2019-09-26 11:47
Maybe you'd want to manage the statusbar yourself if you decide to not have it managed automatically.

**Comment by kesha-antonov** [comment] 2019-09-26 21:11
Yeah
But I think it's better to add new features only if you need them

**Comment by JasperShih** [comment] 2019-10-13 11:16
Great code-trancing skill! But this commitment didn't fix the problem. 
In some situations, text of statusbar still change to white color. I found App will enter your showFullScreenVideoStatusBars function even I didn't click to play a video (but there are some embedded videos in that url page). Actually, I don't know why we need to set UIStatusBarStyleLightContent before entering fullscreen. So I just comment out the line and it works fine for me.

**Comment by partiellkorrekt** [comment] 2019-10-14 06:49
If you don't change the statusbarstyle and your app uses a dark statusbar, the statusbar will be invisible against the black background in fullscreen.

**Comment by partiellkorrekt** [comment] 2019-10-31 11:11
@ancientbuho Your changes look good to me. Have you tested them and can you confirm that the code does what it's supposed to do? This might be good for another pull-request.

**Comment by kesha-antonov** [comment] 2019-10-31 11:44
Why not disable entirely this behaviour for people who don't want auto managing their status bars?

**Comment by ancientbuho** [comment] 2019-10-31 19:34
@partiellkorrekt It fixes the status bar turning white when the keyboard appears, but I haven't had the chance to test that it doesn't break this fix. Once I do I'll send a PR.

**Comment by rmccue** [comment] 2020-01-05 18:32
Hitting this same issue, and had to workaround it with:

```jsx
componentDidMount() {
	// Workaround for https://github.com/react-native-community/react-native-webview/issues/735#issuecomment-548059083
	Keyboard.addListener( 'keyboardWillShow', this.onKeyboardShow );
	StatusBar.setBarStyle( 'dark-content' );
}

componentWillUnmount() {
	Keyboard.removeListener( 'keyboardWillShow', this.onKeyboardShow );
	StatusBar.setBarStyle( 'dark-content' );
}

onKeyboardShow = () => {
	StatusBar.setBarStyle( 'dark-content' );
}
```

Would be great if we could get it fixed in react-native-webview.

**Comment by tyleragnew** [comment] 2020-02-03 19:19
I am seeing this issue as well, but when a keyboardUI is triggered. I was able to fix this by making the following changes to my RNCWebView.m file:

`-(void)showFullScreenVideoStatusBars
{
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
    _isFullScreenVideoOpen = YES;
    RCTUnsafeExecuteOnMainQueueSync(^{
      [RCTSharedApplication() setStatusBarHidden:NO animated:YES];
      [RCTSharedApplication() setStatusBarStyle:RCTSharedApplication().statusBarStyle animated:YES];
    });
#pragma clang diagnostic pop
}

-(void)hideFullScreenVideoStatusBars
{
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
    _isFullScreenVideoOpen = NO;
    RCTUnsafeExecuteOnMainQueueSync(^{
      [RCTSharedApplication() setStatusBarHidden:NO animated:YES];
      [RCTSharedApplication() setStatusBarStyle:RCTSharedApplication().statusBarStyle animated:YES];
    });
#pragma clang diagnostic pop
}`

**Comment by sgehly** [comment] 2020-02-06 00:51
> I am seeing this issue as well, but when a keyboardUI is triggered. I was able to fix this by making the following changes to my RNCWebView.m file:
> 
> ```
> -(void)showFullScreenVideoStatusBars
> {
> #pragma clang diagnostic ignored "-Wdeprecated-declarations"
>     _isFullScreenVideoOpen = YES;
>     RCTUnsafeExecuteOnMainQueueSync(^{
>       [RCTSharedApplication() setStatusBarHidden:NO animated:YES];
>       [RCTSharedApplication() setStatusBarStyle:RCTSharedApplication().statusBarStyle animated:YES];
>     });
> #pragma clang diagnostic pop
> }
> 
> -(void)hideFullScreenVideoStatusBars
> {
> #pragma clang diagnostic ignored "-Wdeprecated-declarations"
>     _isFullScreenVideoOpen = NO;
>     RCTUnsafeExecuteOnMainQueueSync(^{
>       [RCTSharedApplication() setStatusBarHidden:NO animated:YES];
>       [RCTSharedApplication() setStatusBarStyle:RCTSharedApplication().statusBarStyle animated:YES];
>     });
> #pragma clang diagnostic pop
> }
> ```
> 
> I agree with the others, it would be nice to know why the keyboardUi triggers this event in the first place.

I haven't even been working with react-native-webview, and this became an issue through some dependency. I've been looking for the cause of this bug for like three weeks now so thanks for the patch @tyleragnew!

Has this (or something like it) already been patched in RNWebview and my app's dependencies just haven't updated or is this still an open issue?

**Comment by tyleragnew** [comment] 2020-02-06 15:42
> > I am seeing this issue as well, but when a keyboardUI is triggered. I was able to fix this by making the following changes to my RNCWebView.m file:
> > ```
> > -(void)showFullScreenVideoStatusBars
> > {
> > #pragma clang diagnostic ignored "-Wdeprecated-declarations"
> >     _isFullScreenVideoOpen = YES;
> >     RCTUnsafeExecuteOnMainQueueSync(^{
> >       [RCTSharedApplication() setStatusBarHidden:NO animated:YES];
> >       [RCTSharedApplication() setStatusBarStyle:RCTSharedApplication().statusBarStyle animated:YES];
> >     });
> > #pragma clang diagnostic pop
> > }
> > 
> > -(void)hideFullScreenVideoStatusBars
> > {
> > #pragma clang diagnostic ignored "-Wdeprecated-declarations"
> >     _isFullScreenVideoOpen = NO;
> >     RCTUnsafeExecuteOnMainQueueSync(^{
> >       [RCTSharedApplication() setStatusBarHidden:NO animated:YES];
> >       [RCTSharedApplication() setStatusBarStyle:RCTSharedApplication().statusBarStyle animated:YES];
> >     });
> > #pragma clang diagnostic pop
> > }
> > ```
> > 
> > 
> > I agree with the others, it would be nice to know why the keyboardUi triggers this event in the first place.
> 
> I haven't even been working with react-native-webview, and this became an issue through some dependency. I've been looking for the cause of this bug for like three weeks now so thanks for the patch @tyleragnew!
> 
> Has this (or something like it) already been patched in RNWebview and my app's dependencies just haven't updated or is this still an open issue?

Glad that helped @sgehly - I have created an updated issue ticket here: https://github.com/react-native-community/react-native-webview/issues/1190

**Comment by focux** [comment] 2020-04-14 22:11
I'm experiencing this same issue also, even when I navigate from the webview screen to another screen, when I open the keyboard , It automatically change the status bar style to light.

**Comment by focux** [comment] 2020-04-14 22:43
Just tried @tyleragnew fix and it worked perfectly. Thank you so much. It took me several hours to find that the bug was due to the WebView (because It wasn't happening in the WebView screen) and @sgehly found it after 3 weeks because he wasn't using the WebView package directly. As you see, this affects not only the WebView but all the views of an app. I think we should work on a fix for this asap.

If the maintainers don't have the time to fix this, I'd be glad to help. I'm not sure if I should create a PR with @tyleragnew 's fixes or if we should look for another observer instead of `UIWindowDidBecomeVisibleNotification` to detect when someone is playing a video in full screen.

**Comment by ReneMoraales** [comment] 2020-04-14 23:44
I have a different case: when tapping on a file input, the "Take Photo, Photo Library, Browse" shows up, and the StatusBar text turns white.

**Comment by kesha-antonov** [comment] 2020-04-15 08:18
@focux I have PR here https://github.com/react-native-community/react-native-webview/pull/914

But it stuck there for 7 months... Maintainers seems not listening to other developers

**Comment by kesha-antonov** [comment] 2020-04-15 08:21
@Titozzz

**Comment by Saumyadip-Pramanik** [comment] 2020-05-15 07:17
A quick fix can be added by adding `StatusBar.setBarStyle("dark-content");` in **onNavigationStateChange**

```
  onNavigationStateChange = (navState) => {
    StatusBar.setBarStyle("dark-content");
... all other codes
  };
```

**Comment by jamonholmgren** [comment] 2020-06-13 21:22
@kesha-antonov I've reviewed #914 and just have a couple changes.

I also found what I believe to be the source of the light status bar bug, which should fix this issue. See this comment:

https://github.com/react-native-community/react-native-webview/pull/914#discussion_r439770320

**Comment by boraturant** [comment] 2020-07-12 18:29
> I have a different case: when tapping on a file input, as the "Take Photo, Photo Library, Browse" action sheet shows up, the StatusBar text turns white.

+1

Have you managed to find a solution?

**Comment by razzfox** [comment] 2020-08-11 03:31
My use case is using `require()` for a local PDF file as the source. When the PDF loads, the StatusBar text turns white.

**Comment by nupipe** [comment] 2020-08-18 22:54
As a workaround for react native for PDF and navigation:

const darkHandler = () => {
    setTimeout(() => StatusBar.setBarStyle("dark-content"), 3000)
};

<WebView
  onLoad={() => { setLoading(false); darkHandler(); }}
  source={{uri: uriFile }}
  onNavigationStateChange={() => StatusBar.setBarStyle("dark-content")} 
/>

You can adjust the timer.

**Closed** 2020-09-15 00:42 UTC
Labels: Type: bug report

**Comment by ororsatti** [comment] 2022-09-29 10:20
This error still exists, on both IOS and Android.

**Comment by scarlac** [comment] 2022-11-25 19:51
@ororsatti Default behavior was not changed but you can now pass:
```jsx
<WebView autoManageStatusBarEnabled={false} .../>
```
... which disables the unwanted behavior.

The problem may be caused by the Webview component imperatively overriding the bar style which the `<StatusBar />` component sets. So the component gets confused, and so despite having the component in your tree with a specific value, it has no effect.
If you do not want to disable `autoManageStatusBarEnabled` then you need to use the imperative API instead and manage it like so:
```jsx
useEffect(() => { // or useFocusEffect if you're using React Navigation
  StatusBar.setBarStyle('light-content');
});
```

**Comment by pakerwreah** [comment] 2025-01-20 18:20
`13.12.5` here as well.
If I open any screen containing a webview, now every text input starts changing the status bar color when focused.
`autoManageStatusBarEnabled={false}` didn't make any difference for me.

**Comment by denysoleksiienko** [comment] 2025-01-21 08:29
I think need to reopen/create a new issue
