### ISSUE TITLE
HTML File input causes crash in iOS if "Take Photo or Video" option is selected

### ISSUE THREAD

**Issue by DaniAkash** [react-native-community/react-native-webview#214] opened 2018-12-17 11:18 UTC
I have a webview where I have a file input option as below:

```html
<input type="file" name="attach_file" title="" multiple="multiple">
```

Here, if I click on the input and select *Take Photo or Video* option, it causes my application to crash in iOS. It is working fine on Android.

React Native version: 0.57.1
React Native WebView version: 2.14.3
iOS version: 12.1
Device: iPhone SE

**Comment by Titozzz** [comment] 2018-12-18 13:33
duplicate of #208

**Closed by Titozzz** 2018-12-18 13:33 UTC

**Comment by DaniAkash** [comment] 2018-12-19 11:17
@Titozzz I followed the discussion in the issue #208 and added the following to my `info.plist` file

```
         <key>NSCameraUsageDescription</key>
         <string>You can take photos to document your job.</string>
```

Now I'm able to access my camera and take pictures and upload them. However, if I select the video option, it is crashing the app.

**Comment by DaniAkash** [comment] 2018-12-19 11:38
Nevermind, I just found out that video requires microphone and I had to include microphone usage description to my info.plist as well,

```
<key>NSMicrophoneUsageDescription</key>
<string>You can record audio and video using this description key.</string>
```

**Comment by pablolima93** [comment] 2024-05-15 02:09
Galera estou tendo um problema semelhante, tenho um app expo e estou renderizando um site dentro da webview e quando clico em no input file para selecionar uma imagem de perfil funciona, mais quando seleciona a camere e tira a foto o app fecha, e as permissões "NSCameraUsageDescription", "NSPhotoLibraryUsageDescription", "NSMicrophoneUsageDescription"  já estão definidas no app.json ( obs: esse problema só está dando no IOS )

**Comment by renato-grupowell** [comment] 2024-11-18 11:38
Também estou com o mesmo problema, alguma solução?
