### ISSUE TITLE
MIGRATED: App crashes on startup on select environments (Samsung + Android 7 + outdated system WebView) (#18322)

### ISSUE THREAD

**Issue by jamonholmgren** [react-native-community/react-native-webview#14] opened 2018-09-10 00:14 UTC
MIgrated from https://github.com/facebook/react-native/issues/18322

@SeMeKh says:

---

We were seeing a notable amount of crashes on Samsung devices, and after getting hold of a device that kept crashing, we realized that even a freshly react-native inited project crashes on startup.

Environment
Environment:
  OS: Linux 4.15
  Node: 9.8.0
  Yarn: 1.5.1
  npm: 5.7.1
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: ^16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: 0.54.1 => 0.54.1
According to our crash reporter, the crash is limited to Samsung devices running Android 7.0.0.
On these devices, "Android WebView Implementation" is installed with version 0.0.0.1 which looks suspicious.

Workaround
Updating Android WebView Implementation from Play Store fixes the issue.

Stacktrace
```
android.webkit.MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
    at android.webkit.WebViewFactory.getWebViewContextAndSetProvider(WebViewFactory.java:270)
    at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:330)
    at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:194)
    at android.webkit.CookieManager.getInstance(CookieManager.java:39)
    at com.facebook.react.modules.network.ForwardingCookieHandler.getCookieManager(ForwardingCookieHandler.java:158)
    at com.facebook.react.modules.network.ForwardingCookieHandler.get(ForwardingCookieHandler.java:56)
    at okhttp3.JavaNetCookieJar.loadForRequest(JavaNetCookieJar.java:59)
    at com.facebook.react.modules.network.ReactCookieJarContainer.loadForRequest(ReactCookieJarContainer.java:40)
    at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:84)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
    at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
    at okhttp3.RealCall$AsyncCall.execute(RealCall.java:129)
    at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
    at java.lang.Thread.run(Thread.java:762)
android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
    at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:371)
    at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:194)
    at android.webkit.CookieManager.getInstance(CookieManager.java:39)
    at com.facebook.react.modules.network.ForwardingCookieHandler.getCookieManager(ForwardingCookieHandler.java:158)
    at com.facebook.react.modules.network.ForwardingCookieHandler.get(ForwardingCookieHandler.java:56)
    at okhttp3.JavaNetCookieJar.loadForRequest(JavaNetCookieJar.java:59)
    at com.facebook.react.modules.network.ReactCookieJarContainer.loadForRequest(ReactCookieJarContainer.java:40)
    at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:84)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
    at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
    at okhttp3.RealCall$AsyncCall.execute(RealCall.java:129)
    at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
    at java.lang.Thread.run(Thread.java:762)
```

---

_More info on original issue thread_

**Comment by Ehesp** [comment] 2019-04-03 21:07
This is currently out of our control. Closing for now, however if a fix is discovered please let us know when a reproduction/PR and we'll investigate further 👍

**Closed by Ehesp** 2019-04-03 21:07 UTC
Labels: migrated

**Comment by nishantWM** [comment] 2019-06-28 05:50
Shouldn't this be as simple as adding a check for `android.software.webview` before calling it? There's a suggested way [here](https://stackoverflow.com/a/43925989/9994657)

**Comment by cristianoccazinsp** [comment] 2020-10-02 19:50
Looks like this crash is back (or was never resolved). Any ideas?

**Comment by lfoliveir4** [comment] 2022-05-06 23:49
Looks like this crash is back (or was never resolved). Any ideas?

**Comment by otaviogaiao** [comment] 2022-08-29 08:52
It's happening to my app too. Any workaround ?

**Comment by 27leaves** [comment] 2022-11-15 07:23
I also just got a crashlytics report about this. (using react-native)

```
Fatal Exception: android.util.AndroidRuntimeException: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
       at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:363)
       at android.webkit.CookieManager.getInstance(CookieManager.java:50)
       at com.facebook.react.modules.network.ForwardingCookieHandler.getCookieManager(ForwardingCookieHandler.java:136)
       at com.facebook.react.modules.network.ForwardingCookieHandler.get(ForwardingCookieHandler.java:53)
       at okhttp3.JavaNetCookieJar.loadForRequest(JavaNetCookieJar.kt:47)
       at com.facebook.react.modules.network.ReactCookieJarContainer.loadForRequest(ReactCookieJarContainer.java:44)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:74)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)
```
