### ISSUE TITLE
MIGRATED: Input type="file" doesn't work in WebView Android (#16869)

### ISSUE THREAD

**Issue by jamonholmgren** [react-native-community/react-native-webview#11] opened 2018-09-10 00:08 UTC
Migrated from https://github.com/facebook/react-native/issues/16869.

@FelipeBohnertPaetzold says:

---

Environment
Steps to Reproduce
Add a component with WebView pointing to a page that contains a file type input.

Access the component of an Android device.

Expected Behavior
The photo gallery of Android is expected to open to select the desired file.

Actual Behavior
Nothing happens, as if it had clicked out of the input.

Reproducible Demo
https://snack.expo.io/@felipepaetzold/webview-input-file-error-on-android

---

_More info in the original issue thread_

**Comment by andreipfeiffer** [comment] 2018-09-25 13:13
Duplicate of #33, addressed in https://github.com/react-native-community/react-native-webview/pull/60

**Closed** 2018-10-18 03:00 UTC
Labels: duplicate, migrated
