### ISSUE TITLE
WebView make the application crash in release build

### ISSUE THREAD

**Issue by EhteshamAnwar** [react-native-community/react-native-webview#1313] opened 2020-04-10 07:36 UTC
**Bug description:**

I am using react-native-webview library to load webpage, it works fine in debuging, but when I create release build. And click on the tab to load webview , application crashes. following is the error. I have attached error trace as well in the end.

**To Reproduce:**
npx react-native run-android (works) 
npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/ 
cd android 
gradlew assembleRelease   
install the release into device (I get this error)

**Expected behavior:**
it should load web page

**Screenshots/Videos:**
![0MSln](https://user-images.githubusercontent.com/16754151/78972420-2bfa8200-7b27-11ea-9c31-60c2c0a5d612.png)

**Environment:**
 - OS: windows 10
 - OS version:
 - react-native version: 0.62.0
 - react-native-webview version: ^9.0.2

> 2020-04-10 12:20:19.831 3080-3125/com.trackplayer E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
>     Process: com.trackplayer, PID: 3080
>     com.facebook.react.common.JavascriptException: Error: crypto.getRandomValues() not supported. See https://github.com/uuidjs/uuid#getrandomvalues-not-supported
>     
>     This error is located at:
>         in n
>         in RCTView
>         in y
>         in Unknown
>         in Unknown
>         in Unknown
>         in Unknown
>         in RCTView
>         in S
>         in RCTView
>         in RCTView
>         in E
>         in RCTView
>         in c
>         in RCTView
>         in Unknown
>         in v
>         in Unknown
>         in w
>         in Unknown
>         in Unknown
>         in Unknown
>         in Unknown
>         in RCTView
>         in RCTView
>         in RCTView
>         in RCTView
>         in k
>         in ForwardRef
>         in PanGestureHandler
>         in RCTView
>         in k
>         in ForwardRef
>         in RCTView
>         in D
>         in Unknown
>         in RCTView
>         in C
>         in RCTView
>         in H
>         in S
>         in h
>         in RNCSafeAreaView
>         in Unknown
>         in Unknown
>         in GestureHandlerRootView
>         in Unknown
>         in b
>         in Unknown
>         in O
>         in Unknown
>         in ForwardRef
>         in Unknown
>         in ForwardRef
>         in S
>         in RCTView
>         in RCTView
>         in E, stack:
>     default@717:132
>     f@722:329
>     n@714:2621
>     Bn@92:31529
>     ui@92:49357
>     ja@92:72034
>     Oa@92:71959
>     Ia@92:69253
>     Ia@-1
>     <unknown>@92:25480
>     unstable_runWithPriority@183:3503
>     dn@92:25427
>     fn@92:25362
>     Pe@92:90879
>     Re@92:13478
>     Ie@92:13664
>     receiveTouches@92:14448
>     value@27:3544
>     <unknown>@27:840
>     value@27:2798
>     value@27:812
>     value@-1
>     
>         at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:79)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
>         at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
>         at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
>         at android.os.Handler.handleCallback(Handler.java:883)
>         at android.os.Handler.dispatchMessage(Handler.java:100)
>         at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
>         at android.os.Looper.loop(Looper.java:214)
>         at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
>         at java.lang.Thread.run(Thread.java:919)
> 2020-04-10 12:20:19.857 3080-3125/com.trackplayer I/Process: Sending signal. PID: 3080 SIG: 9
>

**Comment by lihop** [comment] 2020-04-10 10:23
Duplicate of #1312

**Comment by HackingGate** [comment] 2020-04-10 10:24
I have the same crash when I upgraded to the latest version.
Downgrade to version less than `v9.1.2` would fix it.
So I think it's a bug that introduced in `v9.1.2`.
I've also tested with `9.0.2`. No crash happened.

`^9.0.2` is not the version you are using.
It will updates to the latest 9.x.x and keep the major version 9.
You can change `^9.0.2` to `~9.0.2` it will keep 9.0.x.
 See [About semantic versioning](https://docs.npmjs.com/about-semantic-versioning).
You can open up npm/yarn lock file to see what version exactly you've installed.

**Comment by EhteshamAnwar** [comment] 2020-04-10 15:15
> I have the same crash when I upgraded to the latest version.
> Downgrade to version less than `v9.1.2` would fix it.
> So I think it's a bug that introduced in `v9.1.2`.
> I've also tested with `9.0.2`. No crash happened.
> 
> `^9.0.2` is not the version you are using.
> It will updates to the latest 9.x.x and keep the major version 9.
> You can change `^9.0.2` to `~9.0.2` it will keep 9.0.x.
> See [About semantic versioning](https://docs.npmjs.com/about-semantic-versioning).
> You can open up npm/yarn lock file to see what version exactly you've installed.

totally unrelated but I used npm install for this library a week ago, how can it install old version?

**Comment by EhteshamAnwar** [comment] 2020-04-10 15:20
> Duplicate of #1312

@lilhop its almost the same problem, but the thing I donot understand is why is it working in the debug build and not in release build, can you please help ?

**Comment by lihop** [comment] 2020-04-11 03:23
@EhteshamAnwar Not sure sorry. I actually came here because I encountered this issue in a development build. I followed the workaround in #1312 and now it is working for me in both debug and release.

Are your sure the screenshot isn't from a development build? Those RedBox errors are automatically disabled in release builds.

**Comment by sibelius** [comment] 2020-04-17 13:08
duplicated of https://github.com/react-native-community/react-native-webview/issues/1312

**Closed by sibelius** 2020-04-17 13:08 UTC
Labels: Type: bug report

**Comment by deepanshu-shopG** [comment] 2020-06-23 12:56
Probable reason:

My theory is release builds generally use proguard for code obfuscation, minification which is causing the problem. Proguard doesn't allow webview to function properly.
This also justifies why it works in the debug build without any issue.

**Comment by aanalmehta-sa** [comment] 2021-05-18 13:57
> Probable reason:
> 
> My theory is release builds generally use proguard for code obfuscation, minification which is causing the problem. Proguard doesn't allow webview to function properly.
> This also justifies why it works in the debug build without any issue.

How to resolve it?
