### ISSUE TITLE
Build failed error: cannot find symbol if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) 

### ISSUE THREAD

**Issue by hipolucas** [react-native-community/react-native-webview#1437] opened 2020-06-04 07:00 UTC
when i run npx react-native run-android build gets failed
i have just installed the package and not imported in app tried build the app give the following build error

Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewModule.java:276: error: cannot find symbol
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
                                                    ^
  symbol:   variable Q
  location: class VERSION_CODES
Note: /node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-webview:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 9s

    at makeError (/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/node_modules/execa/index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Environment:**
 - OS: Mac
 - OS version: 10 .12.6
 - react-native version: 0.62.2
 - react-native-webview version: 10.2.3

**Comment by danilojpferreira** [comment] 2020-06-04 14:18
Same error here! I reverted to 10.1.1 version and it's working.

**Comment by jeffelector** [comment] 2020-06-04 17:58
same with me

**Comment by TasksAndreySorokin** [comment] 2020-06-04 21:10
Same! How install 10.1.1??

**Comment by karthikganesa** [comment] 2020-06-04 21:29
npm i react-native-webview@10.1.1

> Same! How install 10.1.1??

**Comment by yigithanyucedag** [comment] 2020-06-05 04:04
Same here

**Comment by niulinguo** [comment] 2020-06-05 05:19
Same here

**Comment by hipolucas** [comment] 2020-06-05 05:22
downgrading the version works i'm using v9.4.0 now, issue still in latest version.

**Comment by chengsokdara** [comment] 2020-06-05 11:44
I think below commit is the root cause

https://github.com/react-native-community/react-native-webview/commit/03dbcb870eba625d8231bb4808bd91bec70afd85

**Comment by danilojpferreira** [comment] 2020-06-05 12:14
> downgrading the version works i'm using v9.4.0 now, issue still in latest version.

I'm using version 10.1.1 and it is working.

**Comment by msbadar** [comment] 2020-06-08 00:01
Alliteratively you can try by upgrading sdk version to 29 located in `android/build.gradle` 
```   ext {
        buildToolsVersion = "29.0.3"
        minSdkVersion = 21
        compileSdkVersion = 29
        targetSdkVersion = 28
    }
```

**Comment by Great-hijack** [comment] 2020-06-08 11:40
Thanks @msbadar 
It works for me.

**Comment by pulfabio** [comment] 2020-06-11 12:01
@msbadar worked for me too, thanks!

**Comment by danilojpferreira** [comment] 2020-06-12 12:02
> Alliteratively you can try by upgrading sdk version to 29 located in `android/build.gradle`
> 
> ```
>         buildToolsVersion = "29.0.3"
>         minSdkVersion = 21
>         compileSdkVersion = 29
>         targetSdkVersion = 28
>     }
> ```

Also works for me.

**Comment by harshvitra** [comment] 2020-06-15 10:06
Duplicate of #1438 

Solution is posted there

**Comment by mengft** [comment] 2020-06-23 04:11
Change "Build.VERSION_CODES.Q" to "Build.VERSION_CODES.M" like the old version,this works for me

**Closed** 2020-06-30 08:15 UTC
Labels: Type: bug report

**Comment by MagaliCF** [comment] 2020-07-10 14:48
In your code /android/build.gradle file change the next lines. For me works.

`buildscript {
    ext {
        ...
        buildToolsVersion = "29.0.3"
        compileSdkVersion = 29
        ...
    }`

Need to upgrade your compileSdkVersion to 29.

**Comment by ahmedmosad1** [comment] 2021-10-08 22:26
:\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\geolocator_android-2.1.0\android\src\main\java\com\baseflow\geolocator\location\LocationMapper.java:29: error: cannot find symbol
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
                                                    ^
  symbol:   variable S
  location: class VERSION_CODES
E:\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\geolocator_android-2.1.0\android\src\main\java\com\baseflow\geolocator\location\LocationMapper.java:30: error: cannot find symbol
      position.put("is_mocked", location.isMock());
                                        ^
  symbol:   method isMock()
  location: variable location of type Location
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':geolocator_android:compileDebugJavaWithJavac'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.     

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 0s
Running Gradle task 'assembleDebug'...                            121.4s
Exception: Gradle task assembleDebug failed with exit code 1
