### ISSUE TITLE
Custom Fonts not working on iOS when useWebKit={true}

### ISSUE THREAD

**Issue by shukerullah** [react-native-community/react-native-webview#383] opened 2019-03-04 13:52 UTC

**Comment by jamonholmgren** [comment] 2019-03-07 06:41
Hi @shukerullah , can you provide a minimal reproducible app where we can see the issue?

**Comment by shukerullah** [comment] 2019-03-10 10:33
Fonts are working fine on Android and iOS when `useWebkit` is set to `false`.

Here is my code:
```
const headlineBlack = Platform.select({
  ios: `Headline-Black.otf`,
  android: `file:///android_asset/fonts/Headline-Black.otf`
});

const textRoman = Platform.select({
  ios: `Text-Roman.otf`,
  android: `file:///android_asset/fonts/Text-Roman.otf`
});

const html = `<!DOCTYPE html>
  <html>
    <head>
      <meta charset="utf-8" />
      <meta
        name="viewport"
        content="width=device-width; initial-scale=1; maximum-scale=1"
      />
      <style>
        @charset "UTF-8";
        @font-face {
          font-family: "Headline-Black";
          src: url("${headlineBlack}");
        }
        @font-face {
          font-family: "TextRoman";
          src: url("${textRoman}");
        }
      </style>
    </head>
    <body>
      ${content}
    </body>
  </html>`

  <WebView
    source={{
      html,
      baseUrl: "http://localhost/",
    }}
  />
```

**Comment by Titozzz** [comment] 2019-03-14 08:30
Duplicate of #137 you cannot load local file with WKWebView for now.

**Closed by Titozzz** 2019-03-14 08:30 UTC
Labels: need minimal repro

**Comment by maxammann** [comment] 2019-06-07 14:54
@Titozzz in which way is it possible to support this on the react native side? Is there a flag you can set in the webkit webview to allow loading fonts from the documents directory?

I'm thinking of doing a PR to load fonts, but I'm not really sure where the bug here is.

**Comment by httol** [comment] 2019-07-25 07:40
> Duplicate of #137 you cannot load local file with WKWebView for now.

Urgent need to load external files!
Look forward for the update!
Thank you!
