### ISSUE TITLE
onNavigationStateChange doesn't get executed when the webpage is using pushstate routing

### ISSUE THREAD

**Issue by DaniAkash** [react-native-community/react-native-webview#291] opened 2019-01-30 14:35 UTC
I have been using `onNavigationStateChange` method to handle back action for the webpages rendered inside the webview. It works fine for normal pages. 

However, for websites using `history.pushState()` or React Router's [`BrowserRouter`](https://reacttraining.com/react-router/web/api/BrowserRouter) the `onNavigationStateChange` doesn't get called, as a result I'm unable to handle back action (going back when user click android back button)

I have previously found this issue referenced in facebook/react-native#17856 and facebook/react-native#18402 but no proper fix is found yet. 

I'm using react-native-webview version 3.2.2

**Comment by Titozzz** [comment] 2019-01-30 22:34
Yes we are aware, I'm using postmessage to communicate my current state to react native from the Webview .
Closing as duplicate of #24

**Closed by Titozzz** 2019-01-30 22:34 UTC

**Comment by Titozzz** [comment] 2019-01-31 02:10
Using react-router, whenever the current url changes, I do window.postMessage(data, '*') with the new URL inside my data. Complete implementation is ofc a bit different but I think you can get it working with that 💪

**Comment by NestedLooper** [comment] 2019-02-25 14:54
@DaniAkash @Titozzz Example implementation using the latest version of postMessage [here](https://github.com/react-native-community/react-native-webview/issues/24#issuecomment-466546563)

**Comment by KingAmo** [comment] 2019-07-13 11:47
any solution?

**Comment by fondue-tech** [comment] 2023-01-06 10:47
This issue still exists on Android. 3 years later, I have implemented Login framework that communicates with webview and listens to onNavigationStateChange, I started implementing it on IOS and didn't test android letely.
The only solution for now is to make some kind of fallback logic via postMassage as mentiond before. 
I'm sad..
