### ISSUE TITLE
WebView with other components: Other component is not displaying in Android only

### ISSUE THREAD

**Issue by JsonAveza** [react-native-community/react-native-webview#199] opened 2018-12-06 09:43 UTC
Hi Team,

 Currently I upgrade react native version from 0.55 to 0.57 and Added the react-native-webview plugin.
This is my code:
 ` <View style={styles.container}>
           <Text style={styles.welcome}>Welcome to React Native!</Text>
           <WebView
		source={{uri: 'https://facebook.github.io/react-native/'}}
		style={{marginTop: 20}}
	      />
	 </View>`

![image](https://user-images.githubusercontent.com/43028209/49575683-4e93ee00-f969-11e8-8c8d-9c6ed0c218b0.png)

Webpage is loading fine. But Text message not displaying page **(<Text style={styles.welcome}>Welcome to React Native!</Text>)** in **Android ONLY**

Thank You

**Comment by mnoandh** [comment] 2018-12-06 16:19
I am using expo and react native version 0.52.0 .. I have also the same problem

**Comment by Titozzz** [comment] 2018-12-06 22:54
Please add overflow hidden, this is a duplicate of #194 I think? If not, let me know

**Comment by JsonAveza** [comment] 2018-12-07 09:50
@Titozzz 
Thank you.  Its working fine now.

**Closed** 2018-12-07 09:50 UTC
