### ISSUE TITLE
Cannot form weak reference to instance (0x16aaf7c0) of class RNCWKWebView

### ISSUE THREAD

**Issue by davidnum** [react-native-community/react-native-webview#191] opened 2018-12-04 09:49 UTC
Hi. When I move to other screen from screen with web view App crash  with this error:

> objc[6788]: Cannot form weak reference to instance (0x16aaf7c0) of class RNCWKWebView. It is possible that this object was over-released, or is in the process of deallocation.

Iphone 4, IOS 9.3.5

**Comment by Titozzz** [comment] 2018-12-04 10:06
duplicate of #150

**Closed by Titozzz** 2018-12-04 10:06 UTC
