### ISSUE TITLE
White screen on Android

### ISSUE THREAD

**Issue by NikitaSubbotin** [react-native-community/react-native-webview#224] opened 2018-12-31 10:12 UTC
Hi, we are trying to migrate from RN 0.55.2 to 0.57.8. It was suggested to use community library instead of the one within  react-native.

However we have hit a problem where our file viewer is no longer working and was hoping you can help. On iOS all works just as expected, however on Android (8.1) when we try to load our resource we see a blank page. The files which we show are xls and pdf files. They are stored on S3 but we didn't have any luck opening the files direcly from other places as well. All https is setup and working good on previous versions and on 57.8 on Android. On device another browser is opened and file is downloaded rather then shown in the webview

Here the example code: 

```
<WebView
  source={{ uri: http://mtskheta.gov.ge/public/img/1530793528.xlsx }}
  contentContainerStyle={styles.webViewStyle}
  scrollEnabled
  onLoadEnd={this.onLoadEnd}
  allowsInlineMediaPlayback
  mediaPlaybackRequiresUserAction={false}
/>
```

**Comment by romk1n** [comment] 2018-12-31 15:20
same issue

**Comment by Titozzz** [comment] 2019-01-02 10:36
is there any logs on the JS / Native side or when you use web debugging?

**Comment by romk1n** [comment] 2019-01-02 11:19
@Titozzz nothing on my side, and I tried everything whitelists, https, http different xls files.

**Comment by Titozzz** [comment] 2019-01-02 11:19
Can you look at the html code loaded by chrome and paste it here ?

**Comment by romk1n** [comment] 2019-01-02 11:20
@Titozzz not sure what you mean, can you give an example?

**Comment by Titozzz** [comment] 2019-01-02 11:21
Using this: https://github.com/react-native-community/react-native-webview/blob/master/docs/Debugging.md . You can hook your chrome to the device and see potentials bugs with the web inspector

**Comment by x86kernel** [comment] 2019-01-02 11:24
same issue here

**Comment by Titozzz** [comment] 2019-01-02 14:04
@x86kernel same question then 😄

**Comment by NikitaSubbotin** [comment] 2019-01-03 13:59
@Titozzz I tried to debug webview but didn't see any errors

**Comment by Titozzz** [comment] 2019-01-07 13:48
I would need a small reproduction to understand 👍

**Comment by pmontesinos** [comment] 2019-01-10 23:52
This is happening to me too. Here is the file which loads the Webview. Is this what you're asking for?

`import React, {
  Component
} from 'react';
import {
  View,
  StyleSheet,
  Platform
} from 'react-native';
import PropTypes from 'prop-types';
import { connect } from 'react-redux';
import { API } from '../../constants/api';
import Cookie from 'react-native-cookie';
import { requestAnonymousUser } from '../../services/user';
import ModalHeader  from '../../components/navigation/ModalHeader';
import RegistrationConfirmation, { ConfirmationConstants } from '../../components/registration/RegistrationConfirmation';
import navigateTo from '../../services/ScreenNavigator';
import * as AHAsyncStorage from '../../services/AHAsyncStorage';
import { WebView } from 'react-native-webview';
const WEBVIEW_REF = 'registration';

/**
 * Registration webview.
 */
class RegistrationWebview extends Component {

  static propTypes = {
    app: PropTypes.object.isRequired,
    navigator: PropTypes.object.isRequired,
    dispatch: PropTypes.func
  };

  static navigatorStyle = {
    navBarHidden: true
  };

  /**
   * @constructor
   * @param {Object} props
   * @param {Object} props.app - the app properties object.
   * @param {function} props.dispatch - the Redux dispatch function.
   * @param {Object} props.navigator - the Navigator object.
   */
  constructor(props) {
    super(props);
    this.state = {
      confirmationMode: ConfirmationConstants.UNCONFIRMED,
      myJWT: '',
      passProps: JSON.stringify({
        contentKey: 'registration.termsandconditions',
        modalHeaderText: 'Terms and Conditions'
      })
    };

    this.props.navigator.setOnNavigatorEvent(this.onNavigatorEvent.bind(this));
    this.onLoadStart = this.onLoadStart.bind(this);

    // Check if there is a JWT in local storage
    AHAsyncStorage.getItem(AHAsyncStorage.KEYS.MY_JWT).then(JWT => this.setState({myJWT: JWT}));
  }
  /**
   * @ignore
   */
  componentDidMount() {
    requestAnonymousUser({}, true);
  }

  /**
   * @ignore
   */
  componentWillUnmount() {
    AHAsyncStorage.removeItem(AHAsyncStorage.KEYS.USER);
    Cookie.clear(); //clearing the cookie
  }

  setProps() {
    let passProps = this.state.passProps;
    return (
      passProps
    );
  }
  /**
   * Event handler for Navigator events.
   * @param {Object} event
   */
  onNavigatorEvent(event) {
    if (event.type == 'NavBarButtonPress') {
      if (event.id == 'exit') {
        this.props.navigator.dismissModal({
          animationType: 'slide-down'
        });
      }
    }
  }

  /**
   * Event handler for load starts.
   * @param {Object} event
   */
  onLoadStart(event) {
    let url = event.nativeEvent.url;
    if (url.match('confirmation')) {
      this.setState({
        confirmationMode: url.match('fuel-rewards')
          ? ConfirmationConstants.CONFIRMED_FR
          : ConfirmationConstants.CONFIRMED
      });
    }
    this.handleCookies();
  }

  /**
   * @ignore
   */
  onShouldStartLoadWithRequest(event) {
    // [iOS] Intercept certain URLs to display modal and cancel loading page
    if (Platform.OS === 'ios') {
      if (event.url.indexOf('terms-of-use') !== -1) {
        navigateTo(`modal/GenericContentModal/${this.setProps()}`, this.props.navigator);
        return false;
      }
      if (event.url.indexOf('privacy-policy') !== -1) {
        this.displayModal('app.PrivacyPolicyScreen');
        return false;
      }
      else {
        return true;
      }
    }
  }

  /**
   * @ignore
   */
  handleAndroidSecondaryLoads(event) {
    // Need to send to browser for Android users due to no support of onShouldStartLoadWithRequest
    if (Platform.OS === 'android') {
      if (event.url.indexOf('terms-of-use/') !== -1) {
        this.refs[WEBVIEW_REF].stopLoading();
        if (!event.loading) {
          navigateTo(`modal/GenericContentModal/${this.setProps()}`, this.props.navigator);
        }
      }
      if (event.url.indexOf('privacy-policy') !== -1) {
        this.refs[WEBVIEW_REF].stopLoading();
        if (!event.loading) {
          this.displayModal('app.PrivacyPolicyScreen');
        }
      }
    }
  }

  /**
   * Displays modal of given screen and props
   * @param {string} screen - Screen to show.
   * @param {object} prop - Props to pass.
   */
  displayModal(screen, prop = {}) {
    this.props.navigator.showModal({
      screen,
      animationType: 'slide-up',
      passProps: prop
    });
  }

  handleCookies() {
    // Set cookie that hides Download App banner
    Cookie.set(API.BASE_URL, 'sb-closed', 'true');
  }
  /**
   * @ignore
   */
  renderWebview() {
    // in case there is a JWT pass to Registration WebView
    const url = `${API.BASE_URL}/sign-up/?mobileapp=true${this.state.myJWT ? '&idToken=' + this.state.myJWT : ''}`;

    return this.state.confirmationMode === ConfirmationConstants.UNCONFIRMED && (
        <View style={{flex: 1}}>
          <ModalHeader
            navigator={this.props.navigator}
            modalHeaderText={'Registration'}
          />
          <WebView
            ref={WEBVIEW_REF}
            automaticallyAdjustContentInsets={false}
            source={{uri: uri}}
            javaScriptEnabled={true}
            domStorageEnabled={true}
            decelerationRate="normal"
            scalesPageToFit={true}
            startInLoadingState={true}
            onLoadStart={(event) => this.onLoadStart(event)}
            onShouldStartLoadWithRequest={(event) => this.onShouldStartLoadWithRequest(event)}
            onNavigationStateChange={(event) => this.handleAndroidSecondaryLoads(event)}
            backButtonEnabled={true}
            useWebKit={false}
            mixedContentMode={'always'}
            thirdPartyCookiesEnabled={true}
          />
        </View>
      );
  }

  /**
   * @ignore
   */
  renderConfirmation() {
    return (
      <RegistrationConfirmation
        dispatch={this.props.dispatch}
        opco={this.props.app.properties.opco}
        confirmationMode={this.state.confirmationMode}
        navigator={this.props.navigator}
        app={this.props.app}
      />
    );
  }

  /**
   * @ignore
   */
  render() {
    return (
      <View style={style.container}>
        {this.renderWebview()}
        {this.renderConfirmation()}
      </View>
    );
  }
}

const style = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white'
  }
});

function mapStateToProps(state) {
  return {
    app: state.app
  };
}

export default connect(mapStateToProps)(RegistrationWebview);
`
Here is a screenshot of Android emulator and the debugger. As you can see, it's a blank screen and the url is empty in the debugger. Even if I replace the uri with https://google.com, I get the same issue.
![screen shot 2019-01-10 at 5 50 03 pm](https://user-images.githubusercontent.com/3665938/51004456-5151a800-1500-11e9-9898-ee4f92abe817.png)

**Comment by blackinitial** [comment] 2019-01-11 08:59
same here, white screen..
i was installed and link the react-native-webview

dependencies:
```json
"dependencies": {
    "react": "16.6.3",
    "react-native": "0.57.8",
    "react-native-loading-spinner-overlay": "^1.0.1",
    "react-native-webview": "git+https://github.com/react-native-community/react-native-webview.git"
  }
```


my app.js
```jsx
import React, { Component } from 'react';
import { View } from 'react-native';
import { WebView } from 'react-native-webview';
import Spinner from 'react-native-loading-spinner-overlay';

class App extends Component {
  constructor(props) {
    super(props);
    this.state = { visible: true };
  }

  showSpinner() {
    this.setState({ visible: true });
  }

  hideSpinner() {
    this.setState({ visible: false });
  }

  render() {
    let web = 'https://www.instagram.com';
    
    return (
      <View style={{ flex: 1 }}>
        <Spinner
          visible={this.state.visible}
          textContent={'Loading...'}
          textStyle={{ color: '#fff' }}
          />
          <WebView
            scalesPageToFit
            source={{ uri: web }}
            onLoadStart={() => (this.showSpinner())}
            onLoad={() => (this.hideSpinner())}
          />
      </View>
    );
  }
}

export default App;
```

**Comment by Titozzz** [comment] 2019-01-11 09:47
fixed in v3.0.3 cf #241

**Comment by NikitaSubbotin** [comment] 2019-01-11 14:34
@Titozzz I still have white screen. Android is downloading file instead of show it in the webview. Any ideas?

**Comment by Titozzz** [comment] 2019-01-11 14:37
Would this help : https://stackoverflow.com/a/11894771/4022333?

**Comment by cyb3rsalih** [comment] 2019-02-10 21:25
Still have same issue

```

  React Native Environment Info:
    System:
      OS: macOS 10.14.2
      CPU: x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 65.59 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.12.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
      Android SDK:
        Build Tools: 27.0.3, 28.0.3
        API Levels: 23, 24, 26, 27, 28
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0
      react-native: 0.57.0 => 0.57.0
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-rename: 2.4.0

   WebView is up to date
  "react-native-webview": "^5.0.7",
```

**Comment by losheredos** [comment] 2019-02-27 16:54
Facing the same issue.. I thought its cuz of wix navigation, changed it to router-flux still same problem.. It feels like so strange, now I'm trying to downgrade the RN version.....

**Comment by emannick** [comment] 2019-03-05 13:14
Just avoid the nested view. If webview is placed in nested view then it will appear as a blank or white screen.

**Comment by andrewchae** [comment] 2019-03-08 02:31
Is there really no way to get this working with a nested view?

**Comment by Titozzz** [comment] 2019-03-09 00:46
Just use overflow hidden as specified in the docs on the container view

**Comment by ManigandanRaamanathan** [comment] 2019-03-12 08:07
I'm still facing this issue. Any fix? This works fine on iOS. But on android the entire screen become white

**Comment by andrewchae** [comment] 2019-03-12 18:30
@Titozzz setting overflow: hidden makes the screen the background color of the app but content still does not load on screen.

**Comment by jamonholmgren** [comment] 2019-03-17 23:02
We're going to have to rely on the community to help us fix this one, as it's not top of our priority list right now. Hope y'all can help find a solution soon -- happy to review and test when you do!

**Comment by maxschmeling** [comment] 2019-03-20 17:09
I'm having this same issue. I can set the background color of the webview and that will show, but no content will ever load (tried from uri source, html source, local android asset source, and a module/require source).

**Comment by jamonholmgren** [comment] 2019-03-21 02:56
Actually, please submit a new issue with a clear minimal repro so we can copy it into a fresh test app and see the behavior.

**Closed by jamonholmgren** 2019-03-21 02:56 UTC
